# 정리

In [ ]:
from ast import literal_eval
genre_sim_sorted_ind=np.argsort(genre_sim)[:,::-1]
def find_sim_movie(df, sorted_ind, title_name, top_n=10):
    
    # 인자로 입력된 movies_df DataFrame에서 'title' 컬럼이 입력된 title_name 값인 DataFrame추출
    title_movie = df[df['title'] == title_name]
    
    # title_named을 가진 DataFrame의 index 객체를 ndarray로 반환하고 
    # sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n 개의 index 추출
    title_index = title_movie.index.values
    similar_indexes = sorted_ind[title_index, : (top_n)]
    
    # 추출된 top_n index들 출력. top_n index는 2차원 데이터 임. 
    #dataframe에서 index로 사용하기 위해서 1차원 array로 변경
    print(similar_indexes)
    similar_indexes = similar_indexes.reshape(-1)
    
    return df.iloc[similar_indexes] 
soup.find(class_ = "news_tit")




genre_sim = cosine_similarity(genre_mat, genre_mat)
print(genre_sim)
genre_sim_sorted_ind = genre_sim.argsort()[:,::-1] 
percentile = 0.6
m = movies['vote_count'].quantile(percentile) ## 전체에서 60%에 해당되는 수를 최소 투표 횟수로 지정
C = movies['vote_average'].mean() ## 전체 영화에 대한 평점

def weighted_vote_average(record) : 
    v = record['vote_count']    ## 들어온 DataFrame에 대해 투표 횟수로 객체 저장
    R = record['vote_average']  ## 들어온 DataFrame에 대해 개별 영화 평균
    
    return ( (v/(v+m))*R + ((m/m+v))*C )  ## 위의 수식을 Return

## 기존 DataFrame에 weigted_vote_average 칼럼을 추가해줌
movies_df['weighted_vote'] = movies.apply(weighted_vote_average, axis=1)
def find_sim_movie(df, sorted_ind, title_name, top_n = 10) :
    title_movie = df[df['title'] == title_name]
    title_index = title_movie.index.values ## 해당 영화의 index 반환
    
    ## 여기가 바로 argsort를 쓴 이유입니다!! 
    similar_indexes = sorted_ind[title_index, 1 : (top_n*2)] ## 해당 영화에서 가장 유사한 top_n*2개의 영화 추출 
                                                            ## 대신 자기 자신은 제외 !! 
    similar_indexes = similar_indexes.reshape(-1) ## 2차원으로 되어있으므로 1차원으로 바꿔줌 (한줄짜리로!!)
    
    ########## 이러면 similar_indexes 에는 후보군의 index가 담겨있음 ##########
    
    final_list = df.iloc[similar_indexes].sort_values('weighted_vote', ascending=False)[:top_n]
                ## Weighted Vote를 기준으로 내림차순 정렬하고 top_n 만큼만 가져옴 !! 
    return final_list
    
find_sim_movie(movies_df, genre_sim_sorted_ind, 'Avatar', 5)

In [1]:
# 복습문제

In [2]:
1. 분석의 기본 단위로사 NLTK패키지에서 자연어 분석을 위해 만든 샘플 문서 집합
단순히  소설 신문 등의 문서를 모아 놓은 것도 있으면 도서관 시인들의 시집모음 등의 문서 집합 
보조적 의미를 추가하고 보다 쉬운 분석을 위해 구조적인 형태로 정리해 놓은 
말뭉치라는 뜻 서브패키지는 무엇인가? corpus 


다음은 비정형 데이트를 머신러닝에 적용시키기 위한 텍스트 분석의 일환이다. 
알맞은 순서대로 배열하시오. 
2 텍스트 전처리, 피쳐 벡터화/ 추출  머신러닝 모델 수립 및 학습/ 예측/ 평가 

문서와 문서 간의 유사도 비교는 일반적으로 코사인 유사도를 사용합니다.
문서 집합에 숨어 있는 주제를 찾아내는 방법은? 토픽 모델링 

텍스트 분석 패키지 중 주로 소셜 미디어 텍스트에 대한 감성분석을 제공하고, 뛰어난 감성 분석결과 및 
빠른 수행시간으로 대용량 텍스트 데이터에 잘 사용되는 패키지는 ? VADER

자연어를 기계가 이해할 수 있는 숫자의 나열인 벡터로 바꾸어 주어야합니다. : 피처 벡터화 
두 문장에서 같은 단어가 자주 나타나면 코시인 유사도가 높다. 

KMeans 객체의 clusters_centers 속성은 0에서
1의 값을 가지며 0에 가까울수록 중심에 가까운 값이다. (O,X) 
답 : X ..? 

SyntaxError: invalid syntax (240532713.py, line 1)

In [1]:
from nltk import word_tokenize
from nltk.stem import PorterStemmer 


In [2]:
text =  "Now I am going to have dinner with my wife. Thanks for having me here." 

In [3]:
stemmer=PorterStemmer()

In [4]:
words=word_tokenize(text) 

In [5]:
li=[] # 리스트로 된 것은 for반복문 돌려주면 개개에 적용 용이 .
for word in words:
    sword=stemmer.stem(word)
    li.append(sword)
li    

['now',
 'i',
 'am',
 'go',
 'to',
 'have',
 'dinner',
 'with',
 'my',
 'wife',
 '.',
 'thank',
 'for',
 'have',
 'me',
 'here',
 '.']

In [6]:
text =  "Now I am going to have dinner with my wife. Thanks for having me here." 
words = word_tokenize(text)

porter = PorterStemmer()
[porter.stem(word) for word in words] 

['now',
 'i',
 'am',
 'go',
 'to',
 'have',
 'dinner',
 'with',
 'my',
 'wife',
 '.',
 'thank',
 'for',
 'have',
 'me',
 'here',
 '.']

In [7]:
sentence = "Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop. " 


In [8]:
from nltk import word_tokenize, sent_tokenize


In [9]:
ssentence=sent_tokenize(sentence)

In [10]:
len(word_tokenize(sentence))

25

In [11]:
from scipy import sparse

In [12]:
import numpy as np
data = np.array([5,2,3])
row = np.array([2,2,3])
col = np.array([3,4,2])
print(sparse.coo_matrix((data, (row,col)), (5,6)).toarray()) 

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 5 2 0]
 [0 0 3 0 0 0]
 [0 0 0 0 0 0]]


In [13]:
row_index = np.array([0,2,3]) # 이것도 되네?? 
sparse.csr_matrix((data, (row_index, col)), (5,6)).toarray() 

array([[0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)

In [14]:
row_index=np.array([0,0,0,2,3,3])
sparse.csr_matrix((data,col,row_index),shape = (5,6)).toarray()

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 5, 2, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [15]:
row_index = np.array([0,2,3]) # 이것도 되네?? 
sparse.csr_matrix((data, (col, row_index)), (5,6)).toarray() 

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [5, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0]], dtype=int32)

In [16]:
# CSR 형식
data = np.array([5,2,3])
row = np.array([2,2,3])
col = np.array([3,4,2])

from scipy import sparse
sparse.csr_matrix((data, (row, col)), (5,6)).toarray()

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 5, 2, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)

In [17]:
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 4, 5, 2, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

NameError: name 'array' is not defined

In [ ]:


#이 형태 CSR 로 만들려고 하니 어려워서 못하겠습니다. 

data = np.array([4,5,2,3])
row = np.array([0,0,0,3,4,4]) # 일단 처음은 무조건 0/ 0번쨰 행렬 0 /1번째 행렬 0/ 2번째 행렬 3
col = np.array([2,3,4,2])     # 그다음 1개 추가 4, 또없으니까 4+0 
sparse.csr_matrix((data, col, row)).toarray() 

In [ ]:
data = np.array([4,5,2,3])
row = np.array([2,2,2,3])
col = np.array([2,3,4,2])

from scipy import sparse
sparse.csr_matrix((data, (row, col)), (5,6)).toarray()

In [18]:
data =np.array([4,5,2,3]) 
row_index = np.array([0,0,0,3,4,4 ])
col = np.array([2,3,4,2])
sparse.csr_matrix((data, col, row_index)).toarray()

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 4, 5, 2],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0]])

In [19]:
data =np.array([1,2,4,5,2,3]) 
row_index = np.array([0,2,2,5,5,6])
col = np.array([0,1,2,3,4,2])
sparse.csr_matrix((data, col, row_index)).toarray()

array([[1, 2, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 4, 5, 2],
       [0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0]])

In [20]:
M X p @  p X N = M X N  앞의 열과 뒤의 열의 개수가 같아야 함

5 X 5 = 5 X ? @ ? X 5 ?가 아무거나 와도 됨 잠재 행열

SyntaxError: invalid syntax (1865712631.py, line 1)

In [21]:
import pandas as pd

In [22]:
movies= pd.read_csv('tmdb_5000_movies.csv')

In [23]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                4803 non-null   int64  
 1   genres                4803 non-null   object 
 2   homepage              1712 non-null   object 
 3   id                    4803 non-null   int64  
 4   keywords              4803 non-null   object 
 5   original_language     4803 non-null   object 
 6   original_title        4803 non-null   object 
 7   overview              4800 non-null   object 
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object 
 10  production_countries  4803 non-null   object 
 11  release_date          4802 non-null   object 
 12  revenue               4803 non-null   int64  
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object 
 15  status               

In [24]:
movies['genres']

0       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3       [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
                              ...                        
4798    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4799    [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4800    [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4801                                                   []
4802                  [{"id": 99, "name": "Documentary"}]
Name: genres, Length: 4803, dtype: object

In [25]:
# 판다스안 한개의 셀안에 리스트나 딕셔너리 들어가면 안됨 장르의 속성은 오브젝트 걍 텍스트임 

In [26]:
movies['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [27]:
movies['genres'][0][1] # 문자열의 인덱싱을 함 

'{'

In [28]:
from ast import literal_eval

In [29]:
literal_eval('{"id": 28, "name": "Action"}')

{'id': 28, 'name': 'Action'}

In [30]:
type(literal_eval('{"id": 28, "name": "Action"}')) #스트링이 들어가면 파이썬 객체롤 바꿈 

dict

In [31]:
literal_eval(movies['genres'][0])

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [32]:
literal_eval(movies['genres'][0])[0]

{'id': 28, 'name': 'Action'}

In [33]:
literal_eval(movies['genres'][0])[0]['name']

'Action'

In [34]:
movies_df = movies.iloc[:, [3,17,1,18,19,8,4,7]]
movies_df[:2]

id                                     title  \
0  19995                                    Avatar   
1    285  Pirates of the Caribbean: At World's End   

                                              genres  vote_average  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           7.2   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...           6.9   

   vote_count  popularity                                           keywords  \
0       11800  150.437577  [{"id": 1463, "name": "culture clash"}, {"id":...   
1        4500  139.082615  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   

                                            overview  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...

In [35]:
movies_df['genres']=movies_df['genres'].apply(literal_eval)

C:\Users\admin\AppData\Local\Temp\ipykernel_10420\3591631584.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['genres']=movies_df['genres'].apply(literal_eval)


In [36]:
movies_df['keywords']=movies_df['keywords'].apply(literal_eval)

C:\Users\admin\AppData\Local\Temp\ipykernel_10420\2455524115.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['keywords']=movies_df['keywords'].apply(literal_eval)


In [37]:
movies_df['genres'][0]

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [38]:
#장르가 겹치면 유사하다. 각 장르 글자 뽑아내자 

In [39]:
for i in movies_df['genres'][0]:
    print(i)

{'id': 28, 'name': 'Action'}
{'id': 12, 'name': 'Adventure'}
{'id': 14, 'name': 'Fantasy'}
{'id': 878, 'name': 'Science Fiction'}


In [40]:
for i in movies_df['genres'][0]:
    for j in i:
        print(i[j])

28
Action
12
Adventure
14
Fantasy
878
Science Fiction


In [41]:
for i in movies_df['genres'][0]:
    print(i['name'])

Action
Adventure
Fantasy
Science Fiction


In [42]:
[i['name'] for i in movies_df['genres'][0]]

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [43]:
[i['name'] for i in movies_df['genres']]

TypeError: list indices must be integers or slices, not str

In [44]:
movies_df['genres']= movies_df['genres'].apply(lambda x : [y['name'] for y in x])# apply에서 각 한 셀에 접근 
movies_df['keywords']= movies_df['keywords'].apply(lambda x : [y['name'] for y in x])# apply에서 각 한 셀에 접근 

C:\Users\admin\AppData\Local\Temp\ipykernel_10420\2281509907.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['genres']= movies_df['genres'].apply(lambda x : [y['name'] for y in x])# apply에서 각 한 셀에 접근
C:\Users\admin\AppData\Local\Temp\ipykernel_10420\2281509907.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['keywords']= movies_df['keywords'].apply(lambda x : [y['name'] for y in x])# apply에서 각 한 셀에 접근


In [45]:
movies_df[:2]

id                                     title  \
0  19995                                    Avatar   
1    285  Pirates of the Caribbean: At World's End   

                                          genres  vote_average  vote_count  \
0  [Action, Adventure, Fantasy, Science Fiction]           7.2       11800   
1                   [Adventure, Fantasy, Action]           6.9        4500   

   popularity                                           keywords  \
0  150.437577  [culture clash, future, space war, space colon...   
1  139.082615  [ocean, drug abuse, exotic island, east india ...   

                                            overview  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...

In [46]:
from sklearn.feature_extraction.text import CountVectorizer

In [47]:
count_vect =CountVectorizer(min_df=0, ngram_range=(1,2))

In [48]:
movies_df['genres_literal']= movies_df['genres'].apply(lambda x : " ".join(x))# apply에서 각 한 셀에 접근 


C:\Users\admin\AppData\Local\Temp\ipykernel_10420\3169800080.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['genres_literal']= movies_df['genres'].apply(lambda x : " ".join(x))# apply에서 각 한 셀에 접근


In [49]:
movies_df[:2]

id                                     title  \
0  19995                                    Avatar   
1    285  Pirates of the Caribbean: At World's End   

                                          genres  vote_average  vote_count  \
0  [Action, Adventure, Fantasy, Science Fiction]           7.2       11800   
1                   [Adventure, Fantasy, Action]           6.9        4500   

   popularity                                           keywords  \
0  150.437577  [culture clash, future, space war, space colon...   
1  139.082615  [ocean, drug abuse, exotic island, east india ...   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   

                             genres_literal  
0  Action Adventure Fantasy Science Fiction  
1                  Adventure Fantasy Action

In [50]:
genre_mat=count_vect.fit_transform(movies_df['genres_literal'])

In [51]:
genre_mat.shape

(4803, 276)

In [52]:
genre_mat[0]

<1x276 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [53]:
from sklearn.metrics.pairwise import cosine_similarity

In [54]:
cosine_similarity(genre_mat[0], genre_mat[0]) # 자기와 자기는 같음

array([[1.]])

In [55]:
cosine_similarity(genre_mat, genre_mat) # 대각은 1 

array([[1.        , 0.59628479, 0.4472136 , ..., 0.        , 0.        ,
        0.        ],
       [0.59628479, 1.        , 0.4       , ..., 0.        , 0.        ,
        0.        ],
       [0.4472136 , 0.4       , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [56]:
a=np.array([11,10,13,12])
np.sort(a)

array([10, 11, 12, 13])

In [57]:
np.argsort(a)[::-1]

array([2, 3, 0, 1], dtype=int64)

In [58]:
a[np.argsort(a)[::-1]]

array([13, 12, 11, 10])

In [59]:
genre_sim=cosine_similarity(genre_mat, genre_mat) # 대각은 1 
genre_sim

array([[1.        , 0.59628479, 0.4472136 , ..., 0.        , 0.        ,
        0.        ],
       [0.59628479, 1.        , 0.4       , ..., 0.        , 0.        ,
        0.        ],
       [0.4472136 , 0.4       , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [60]:
np.argsort(genre_sim) # 유사도가 낮은 것 부터 높은 순서로 가는 인덱스 번호 

array([[2401, 3037, 3038, ...,  813, 3494,    0],
       [2401, 3067, 3069, ...,  129,    1,  262],
       [2401, 2999, 3000, ..., 1542, 1740,    2],
       ...,
       [   0, 2230, 2229, ..., 1895, 3809, 4800],
       [   0, 3205, 3204, ..., 1596, 1594, 4802],
       [   0, 3141, 3140, ..., 4521, 4710, 4802]], dtype=int64)

In [61]:
genre_sim_sorted_ind=np.argsort(genre_sim)[:,::-1]
genre_sim_sorted_ind

array([[   0, 3494,  813, ..., 3038, 3037, 2401],
       [ 262,    1,  129, ..., 3069, 3067, 2401],
       [   2, 1740, 1542, ..., 3000, 2999, 2401],
       ...,
       [4800, 3809, 1895, ..., 2229, 2230,    0],
       [4802, 1594, 1596, ..., 3204, 3205,    0],
       [4802, 4710, 4521, ..., 3140, 3141,    0]], dtype=int64)

In [62]:
genre_sim_sorted_ind[0]

array([   0, 3494,  813, ..., 3038, 3037, 2401], dtype=int64)

In [63]:
np.argsort(genre_sim)[:, ::-1][0]

array([   0, 3494,  813, ..., 3038, 3037, 2401], dtype=int64)

In [64]:
movies_df.iloc[np.argsort(genre_sim)[:, ::-1][0], :] 

id                                      title  \
0      19995                                     Avatar   
3494   27549  Beastmaster 2: Through the Portal of Time   
813     1924                                   Superman   
870     8536                                Superman II   
46    127585                 X-Men: Days of Future Past   
...      ...                                        ...   
3041   27322                                 Love Jones   
3039   75900                       My Week with Marilyn   
3038   17710                      Hey Arnold! The Movie   
3037   19905            The Goods: Live Hard, Sell Hard   
2401   31932                             City of Ghosts   

                                             genres  vote_average  vote_count  \
0     [Action, Adventure, Fantasy, Science Fiction]           7.2       11800   
3494  [Action, Adventure, Fantasy, Science Fiction]           4.6          17   
813   [Action, Adventure, Fantasy, Science Fiction]           6.9        1022   
870   [Action, Adventure, Fantasy, Science Fiction]           6.5         629   
46    [Action, Adventure, Fantasy, Science Fiction]           7.5        6032   
...                                             ...           ...         ...   
3041                       [Comedy, Drama, Romance]           8.1          12   
3039                                        [Drama]           6.6         406   
3038                            [Animation, Family]           5.6          62   
3037                                       [Comedy]           5.4          58   
2401                                     [Thriller]           5.4          18   

      popularity                                           keywords  \
0     150.437577  [culture clash, future, space war, space colon...   
3494    1.478505  [based on novel, time travel, sequel, psychotr...   
813    48.507081  [saving the world, journalist, dc comics, crim...   
870    30.515175  [saving the world, dc comics, sequel, superher...   
46    118.078691  [1970s, mutant, time travel, marvel comic, bas...   
...          ...                                                ...   
3041    1.000178  [sex, ex-boyfriend, independent film, african ...   
3039   21.006078  [based on novel, biography, historical figure,...   
3038    5.856363                                                 []   
3037    3.352702                             [duringcreditsstinger]   
2401    2.644860                                                 []   

                                               overview  \
0     In the 22nd century, a paraplegic Marine is di...   
3494  Mark Singer returns as Dar, the warrior who ca...   
813   Mild-mannered Clark Kent works as a reporter a...   
870   Three escaped criminals from the planet Krypto...   
46    The ultimate X-Men ensemble fights a war for t...   
...                                                 ...   
3041  Darius Lovehall is a young black poet in Chica...   
3039  Sir Laurence Olivier is making a movie in Lond...   
3038  When a powerful developer named Mr. Scheck wan...   
3037  Who is Don Ready? Salesman? Lover? Song Stylis...   
2401  A con man (Dillon) travels to Cambodia (also o...   

                                genres_literal  
0     Action Adventure Fantasy Science Fiction  
3494  Action Adventure Fantasy Science Fiction  
813   Action Adventure Fantasy Science Fiction  
870   Action Adventure Fantasy Science Fiction  
46    Action Adventure Fantasy Science Fiction  
...                                        ...  
3041                      Comedy Drama Romance  
3039                                     Drama  
3038                          Animation Family  
3037                                    Comedy  
2401                                  Thriller  

[4803 rows x 9 columns]

In [65]:
def find_sim_movie(df, sorted_ind, title_name, top_n=10):
    
    # 인자로 입력된 movies_df DataFrame에서 'title' 컬럼이 입력된 title_name 값인 DataFrame추출
    title_movie = df[df['title'] == title_name]
    
    # title_named을 가진 DataFrame의 index 객체를 ndarray로 반환하고 
    # sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n 개의 index 추출
    title_index = title_movie.index.values
    similar_indexes = sorted_ind[title_index, : (top_n)]
    
    # 추출된 top_n index들 출력. top_n index는 2차원 데이터 임. 
    #dataframe에서 index로 사용하기 위해서 1차원 array로 변경
    print(similar_indexes)
    similar_indexes = similar_indexes.reshape(-1)
    
    return df.iloc[similar_indexes] 

In [66]:
df=movies_df.copy()
title_movie=df[df['title']=='The Godfather']
title_movie

id          title          genres  vote_average  vote_count  \
3337  238  The Godfather  [Drama, Crime]           8.4        5893   

      popularity                                           keywords  \
3337  143.659698  [italy, love at first sight, loss of father, p...   

                                               overview genres_literal  
3337  Spanning the years 1945 to 1955, a chronicle o...    Drama Crime

In [67]:
title_index=title_movie.index.values

In [68]:
similar_indexes = sorted_ind[title_index, :(top_n)]

NameError: name 'sorted_ind' is not defined

In [ ]:
find_sim_movie(movies_df, genre_sim_sorted_ind, 'The Godfather', 10)

In [ ]:
(v/ v+m)*0.6   (m/v+m)*0.4 # v에 더 가중치 둔다. 

In [ ]:
(v/ v+m)*R  + (m/v+m)*C # v에 더 가중치 둔다. 

In [ ]:
movies_df['vote_count'].value_counts()

In [69]:
movies_df['vote_count']=movies_df['vote_count'].replace(0,1)

C:\Users\admin\AppData\Local\Temp\ipykernel_10420\3316143438.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['vote_count']=movies_df['vote_count'].replace(0,1)


In [70]:
movies_df['vote_count'].value_counts()

1       115
2        46
4        43
3        41
6        38
       ... 
4048      1
648       1
5862      1
3583      1
2078      1
Name: vote_count, Length: 1608, dtype: int64

In [71]:
C = movies_df['vote_average'].mean()
m = movies_df['vote_count'].quantile(0.6)
print(C,  m)

def weighted_vote_avarage(record):
    v =record['vote_count']
    R =record['vote_average']
    
    return ((v/(v+m))*R + (m/m+v)*C)

6.092171559442011 370.1999999999998


In [72]:
movies_df['weighted_vote']=movies_df.apply(weighted_vote_avarage, axis=1)

C:\Users\admin\AppData\Local\Temp\ipykernel_10420\3710418450.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['weighted_vote']=movies_df.apply(weighted_vote_avarage, axis=1)


In [73]:
movies_df.apply(weighted_vote_avarage, axis=1)

0       71900.697559
1       27427.239697
2       27219.548106
3       55488.709488
4       12951.059175
            ...     
4798     1458.611706
4799       36.631654
4800       42.756844
4801       48.843152
4802      103.827921
Length: 4803, dtype: float64

In [74]:
def find_sim_movie(df, sorted_ind, title_name, top_n=10):
    title_movie = df[df['title'] == title_name]
    title_index = title_movie.index.values
    
    # top_n의 2배에 해당하는 쟝르 유사성이 높은 index 추출 
    similar_indexes = sorted_ind[title_index, :(top_n*2)]
    similar_indexes = similar_indexes.reshape(-1)
# 기준 영화 index는 제외
    similar_indexes = similar_indexes[similar_indexes != title_index]
    
    # top_n의 2배에 해당하는 후보군에서 weighted_vote 높은 순으로 top_n 만큼 추출 
    return df.iloc[similar_indexes].sort_values('weighted_vote', ascending=False)[:top_n]

similar_movies = find_sim_movie(movies_df, genre_sim_sorted_ind, 'The Godfather',10)
similar_movies[['title', 'vote_average', 'weighted_vote']] 

title  vote_average  weighted_vote
883               Catch Me If You Can           7.7   23132.898869
2731           The Godfather: Part II           8.3   20349.232225
1847                       GoodFellas           8.2   19069.737037
1149                  American Hustle           6.8   17112.825419
3866                      City of God           8.1   11064.018512
281                 American Gangster           7.4    9162.470613
1663      Once Upon a Time in America           8.2    6524.714313
588   Wall Street: Money Never Sleeps           5.8    3012.845308
2839                         Rounders           6.9    2684.298813
4041                  This Is England           7.4    2221.214114

In [75]:
from surprise import SVD
from surprise import Dataset
from surprise import accuracy
from surprise.model_selection import train_test_split

In [76]:
data = Dataset.load_builtin('ml-100k', prompt=False)

In [77]:
trainset, testset =train_test_split(data, test_size=.25, random_state=0)

In [78]:
algo =SVD(random_state=0)
algo.fit(trainset)

In [79]:
preds=algo.test(testset)
preds # rui 와 est 차이

[Prediction(uid='120', iid='282', r_ui=4.0, est=3.5114147666251547, details={'was_impossible': False}),
 Prediction(uid='882', iid='291', r_ui=4.0, est=3.573872419581491, details={'was_impossible': False}),
 Prediction(uid='535', iid='507', r_ui=5.0, est=4.033583485472447, details={'was_impossible': False}),
 Prediction(uid='697', iid='244', r_ui=5.0, est=3.8463639495936905, details={'was_impossible': False}),
 Prediction(uid='751', iid='385', r_ui=4.0, est=3.1807542478219157, details={'was_impossible': False}),
 Prediction(uid='219', iid='82', r_ui=1.0, est=4.1755161590745145, details={'was_impossible': False}),
 Prediction(uid='279', iid='571', r_ui=4.0, est=2.4179600970240775, details={'was_impossible': False}),
 Prediction(uid='429', iid='568', r_ui=3.0, est=3.062893143794347, details={'was_impossible': False}),
 Prediction(uid='456', iid='100', r_ui=3.0, est=4.51573882377166, details={'was_impossible': False}),
 Prediction(uid='249', iid='23', r_ui=4.0, est=4.76990278783951, detai

In [80]:
preds[0] # est 예측 점수/ r_ui 실제점수 

Prediction(uid='120', iid='282', r_ui=4.0, est=3.5114147666251547, details={'was_impossible': False})

In [81]:
[(pred.uid, pred.iid, pred.est) for pred in preds[:3]]

[('120', '282', 3.5114147666251547),
 ('882', '291', 3.573872419581491),
 ('535', '507', 4.033583485472447)]

In [82]:
pred = algo.predict(str(196), str(302))

In [83]:
pred

Prediction(uid='196', iid='302', r_ui=None, est=4.494386477040736, details={'was_impossible': False})

In [84]:
accuracy.rmse(preds)

RMSE: 0.9467


0.9466860806937948

In [85]:
rating= pd.read_csv('ratings.csv')

In [86]:
rating

userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [87]:
rating.to_csv('ratings_noh.csv', index=False, header=False)

In [88]:
pd.read_csv('ratings_noh.csv')

1     1.1  4.0   964982703
0         1       3  4.0   964981247
1         1       6  4.0   964982224
2         1      47  5.0   964983815
3         1      50  5.0   964982931
4         1      70  3.0   964982400
...     ...     ...  ...         ...
100830  610  166534  4.0  1493848402
100831  610  168248  5.0  1493850091
100832  610  168250  5.0  1494273047
100833  610  168252  5.0  1493846352
100834  610  170875  3.0  1493846415

[100835 rows x 4 columns]

In [89]:
from surprise import Reader

In [90]:
- sep=" " 
 이 옵션을 이용하게 되면 print문의 출력문들 사이에 해당하는 내용을 넣을 수 있습니다. 
    기본 값으로는 공백이 들어가 있으며
    이를 사용해 원하는 문자를 입력할 수 있습니다.

SyntaxError: cannot assign to operator (1883094920.py, line 1)

In [91]:
reader=Reader(line_format='user item rating timestamp', sep=',' , rating_scale=(0.5, 5))
data =Dataset.load_from_file('ratings_noh.csv', reader=reader)

In [92]:
data

In [ ]:
trainset, testset =train_test_split(data, test_size=.25, random_state=0)
algo =SVD(n_factors=50, random_state=0)
algo.fit(trainset)
preds =algo.test(testset)
accuracy.rmse(preds)

RMSE: 0.8682


0.8681952927143516

In [ ]:
5 X 5 = 5 X p @ p X 5 

SyntaxError: invalid syntax (3102325644.py, line 1)

In [ ]:
베이스 라인 평점 일관되게 평점 안좋게 줌 

In [ ]:
import urllib.request

In [95]:
from urllib import request

In [96]:
from bs4 import BeautifulSoup

In [97]:
url ="https://search.naver.com/search.naver?where=news&sm=tab_jum&query=%ED%94%84%EB%9E%91%EC%8A%A4"

In [98]:
html=request.urlopen(url).read()
html # ctrl F  찾기 

b'<!doctype html> <html lang="ko"> <head> <meta charset="utf-8"> <meta name="referrer" content="always">  <meta name="format-detection" content="telephone=no,address=no,email=no"> <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=2.0"> <meta property="og:title" content="\xed\x94\x84\xeb\x9e\x91\xec\x8a\xa4 : \xeb\x84\xa4\xec\x9d\xb4\xeb\xb2\x84 \xeb\x89\xb4\xec\x8a\xa4\xea\xb2\x80\xec\x83\x89"/> <meta property="og:image" content="https://ssl.pstatic.net/sstatic/search/common/og_v3.png"> <meta property="og:description" content="\'\xed\x94\x84\xeb\x9e\x91\xec\x8a\xa4\'\xec\x9d\x98 \xeb\x84\xa4\xec\x9d\xb4\xeb\xb2\x84 \xeb\x89\xb4\xec\x8a\xa4\xea\xb2\x80\xec\x83\x89 \xea\xb2\xb0\xea\xb3\xbc\xec\x9e\x85\xeb\x8b\x88\xeb\x8b\xa4."> <meta name="description" lang="ko" content="\'\xed\x94\x84\xeb\x9e\x91\xec\x8a\xa4\'\xec\x9d\x98 \xeb\x84\xa4\xec\x9d\xb4\xeb\xb2\x84 \xeb\x89\xb4\xec\x8a\xa4\xea\xb2\x80\xec\x83\x89 \xea\xb2\xb0\xea\xb3\xbc\xec\x9e\x85\xeb\x8b\x88\

In [99]:
soup= BeautifulSoup(html, 'html.parser')

# 파이썬에서는 딕셔너리 일반적으로는 json

In [100]:
soup.find_all("title")

[<title>프랑스 : 네이버 뉴스검색</title>]

In [71]:
title=soup.find_all(class_ = "news_tit")

In [72]:
soup.find(class_ = "news_tit")


<a class="news_tit" href="https://www.yna.co.kr/view/AKR20221026076300054?input=1195m" onclick="return goOtherCR(this, 'a=nws*a.tit&amp;r=1&amp;i=880000D8_000000000000000013531625&amp;g=001.0013531625&amp;u='+urlencode(this.href));" target="_blank" title="보성 차·쌀, 프랑스 통해 유럽 시장 진출한다">보성 차·쌀, <mark>프랑스</mark> 통해 유럽 시장 진출한다</a>

In [73]:
len(title)

10

In [74]:
title[0]

<a class="news_tit" href="https://www.yna.co.kr/view/AKR20221026076300054?input=1195m" onclick="return goOtherCR(this, 'a=nws*a.tit&amp;r=1&amp;i=880000D8_000000000000000013531625&amp;g=001.0013531625&amp;u='+urlencode(this.href));" target="_blank" title="보성 차·쌀, 프랑스 통해 유럽 시장 진출한다">보성 차·쌀, <mark>프랑스</mark> 통해 유럽 시장 진출한다</a>

In [75]:
title[0].text

'보성 차·쌀, 프랑스 통해 유럽 시장 진출한다'

In [76]:
li= []
for i in range(len(title)):
    ti =title[i].text
    li.append(ti)
li    

['보성 차·쌀, 프랑스 통해 유럽 시장 진출한다',
 "프랑스 관광청, 'French Days in Seoul 2022' 행사 성황리 개최",
 '천안시, 프랑스 기업과 660억원 규모 투자협약',
 '에어프랑스, 기차 연계 여행 ‘트레인+에어’ 서비스 강화',
 '숭실대 GTEP사업단, 프랑스 파리 SIAL 참가해 현장 계약 52만 달러 달성',
 '오세훈 "프랑스 시작으로 K뷰티 해외 진출 돕겠다"',
 "컬리, 프랑스 식품 브랜드 '피카드' 국내 단독 론칭 예정",
 '‘프랑스 약국 직구템’ 덱세릴, 국내 들어온다',
 '투썸플레이스, 프랑스식 디저트 ‘다쿠아즈 에뻬’ 선봬',
 "'디펜딩 챔피언' 프랑스, 20년전 못 이룬 '월드컵 2연패' 해낼까?"]

In [79]:
for i in range(len(title)):
          print(title[i].text) 

보성 차·쌀, 프랑스 통해 유럽 시장 진출한다
프랑스 관광청, 'French Days in Seoul 2022' 행사 성황리 개최
천안시, 프랑스 기업과 660억원 규모 투자협약
에어프랑스, 기차 연계 여행 ‘트레인+에어’ 서비스 강화
숭실대 GTEP사업단, 프랑스 파리 SIAL 참가해 현장 계약 52만 달러 달성
오세훈 "프랑스 시작으로 K뷰티 해외 진출 돕겠다"
컬리, 프랑스 식품 브랜드 '피카드' 국내 단독 론칭 예정
‘프랑스 약국 직구템’ 덱세릴, 국내 들어온다
투썸플레이스, 프랑스식 디저트 ‘다쿠아즈 에뻬’ 선봬
'디펜딩 챔피언' 프랑스, 20년전 못 이룬 '월드컵 2연패' 해낼까?


In [272]:
[title[i].text for i in range(len(title)) ] 


['보성 차·쌀, 프랑스 통해 유럽 시장 진출한다',
 '천안시, 프랑스 기업과 660억원 규모 투자협약',
 '숭실대 GTEP사업단, 프랑스 파리 SIAL 참가해 현장 계약 52만 달러 달성',
 '에어프랑스, 기차 연계 여행 ‘트레인+에어’ 서비스 강화',
 '오세훈 "프랑스 시작으로 K뷰티 해외 진출 돕겠다"',
 "컬리, 프랑스 식품 브랜드 '피카드' 국내 단독 론칭 예정",
 '‘프랑스 약국 직구템’ 덱세릴, 국내 들어온다',
 '투썸플레이스, 프랑스식 디저트 ‘다쿠아즈 에뻬’ 선봬',
 "'디펜딩 챔피언' 프랑스, 20년전 못 이룬 '월드컵 2연패' 해낼까?",
 "마켓컬리, 프랑스 국민 식품 브랜드 '피카드' 론칭"]

In [80]:
for tit in title:
    print(tit.text)

보성 차·쌀, 프랑스 통해 유럽 시장 진출한다
프랑스 관광청, 'French Days in Seoul 2022' 행사 성황리 개최
천안시, 프랑스 기업과 660억원 규모 투자협약
에어프랑스, 기차 연계 여행 ‘트레인+에어’ 서비스 강화
숭실대 GTEP사업단, 프랑스 파리 SIAL 참가해 현장 계약 52만 달러 달성
오세훈 "프랑스 시작으로 K뷰티 해외 진출 돕겠다"
컬리, 프랑스 식품 브랜드 '피카드' 국내 단독 론칭 예정
‘프랑스 약국 직구템’ 덱세릴, 국내 들어온다
투썸플레이스, 프랑스식 디저트 ‘다쿠아즈 에뻬’ 선봬
'디펜딩 챔피언' 프랑스, 20년전 못 이룬 '월드컵 2연패' 해낼까?


In [277]:
[tit.text for tit in title] 

['보성 차·쌀, 프랑스 통해 유럽 시장 진출한다',
 '천안시, 프랑스 기업과 660억원 규모 투자협약',
 '숭실대 GTEP사업단, 프랑스 파리 SIAL 참가해 현장 계약 52만 달러 달성',
 '에어프랑스, 기차 연계 여행 ‘트레인+에어’ 서비스 강화',
 '오세훈 "프랑스 시작으로 K뷰티 해외 진출 돕겠다"',
 "컬리, 프랑스 식품 브랜드 '피카드' 국내 단독 론칭 예정",
 '‘프랑스 약국 직구템’ 덱세릴, 국내 들어온다',
 '투썸플레이스, 프랑스식 디저트 ‘다쿠아즈 에뻬’ 선봬',
 "'디펜딩 챔피언' 프랑스, 20년전 못 이룬 '월드컵 2연패' 해낼까?",
 "마켓컬리, 프랑스 국민 식품 브랜드 '피카드' 론칭"]

In [274]:
title[0].attrs['href'] # 링크가져오기 

'https://www.yna.co.kr/view/AKR20221026076300054?input=1195m'

In [275]:
li= []
for i in range(len(title)):
    ti =title[i].attrs['href']
    li.append(ti)
li    

['https://www.yna.co.kr/view/AKR20221026076300054?input=1195m',
 'http://www.newsis.com/view/?id=NISX20221026_0002061890&cID=10807&pID=10800',
 'http://edu.donga.com/?p=article&ps=view&at_no=20221026104031835035',
 'http://news.heraldcorp.com/view.php?ud=20221026000115',
 'https://www.sedaily.com/NewsView/26CHLF62AH',
 'http://star.mt.co.kr/stview.php?no=2022102410562846748',
 'http://www.kukinews.com/newsView/kuk202210250092',
 'https://view.asiae.co.kr/article/2022102610252640732',
 'http://www.ohmynews.com/NWS_Web/View/at_pg.aspx?CNTN_CD=A0002875144&CMPT_CD=P0010&utm_source=naver&utm_medium=newsearch&utm_campaign=naver_news',
 'http://moneys.mt.co.kr/news/mwView.php?no=2022102511232598355']

In [276]:
for i in title: 
    print(i.text, " : ", i.attrs['href'])

보성 차·쌀, 프랑스 통해 유럽 시장 진출한다  :  https://www.yna.co.kr/view/AKR20221026076300054?input=1195m
천안시, 프랑스 기업과 660억원 규모 투자협약  :  http://www.newsis.com/view/?id=NISX20221026_0002061890&cID=10807&pID=10800
숭실대 GTEP사업단, 프랑스 파리 SIAL 참가해 현장 계약 52만 달러 달성  :  http://edu.donga.com/?p=article&ps=view&at_no=20221026104031835035
에어프랑스, 기차 연계 여행 ‘트레인+에어’ 서비스 강화  :  http://news.heraldcorp.com/view.php?ud=20221026000115
오세훈 "프랑스 시작으로 K뷰티 해외 진출 돕겠다"  :  https://www.sedaily.com/NewsView/26CHLF62AH
컬리, 프랑스 식품 브랜드 '피카드' 국내 단독 론칭 예정  :  http://star.mt.co.kr/stview.php?no=2022102410562846748
‘프랑스 약국 직구템’ 덱세릴, 국내 들어온다  :  http://www.kukinews.com/newsView/kuk202210250092
투썸플레이스, 프랑스식 디저트 ‘다쿠아즈 에뻬’ 선봬  :  https://view.asiae.co.kr/article/2022102610252640732
'디펜딩 챔피언' 프랑스, 20년전 못 이룬 '월드컵 2연패' 해낼까?  :  http://www.ohmynews.com/NWS_Web/View/at_pg.aspx?CNTN_CD=A0002875144&CMPT_CD=P0010&utm_source=naver&utm_medium=newsearch&utm_campaign=naver_news
마켓컬리, 프랑스 국민 식품 브랜드 '피카드' 론칭  :  http://moneys.mt.co.kr/news/mwView.php?no=

In [235]:
컨텐츠 기반 필터링 추천 시스템

(Content Based Filtering Recommend System)

컨텐츠 기반 추천시스템은 굉장히 직관적입니다. 이 시스템이 추천해주는 방식을 결국 생각해보면 

"너 이거 좋아해? 그럼 이 종류도 좋아하겠네?" 입니다. 마카롱을 좋아하는 친구에게 다쿠아즈도 좋아하겠네? 라고 말하는 거랑 똑같죠. 


즉, 특정 아이템을 선호한다고 할 때, 비슷한 컨텐츠를 가지는 다른 아이템을 추천하는 방식입니다.
방법은 굉장히 직관적입니다. 그럼 이런 직관적인 방식을 어떻게 추천하도록 만들 수 있을까요?


먼저 컨텐츠 기반 필터링 추천시스템의 과정은 아래로 요약할 수 있습니다.


1. 영화 구성 컨텐츠 text 처리

2. Feature Vectorization

3. Cosine Similarity 측정

4. 기준에 의한 추천





SyntaxError: invalid syntax (570684263.py, line 1)

# 텍스트 처리

In [240]:
import pandas as pd
import numpy as np
import warnings; warnings.filterwarnings('ignore')

movies = pd.read_csv('./tmdb_5000_movies.csv')
print(movies.shape)

movies.head()
import pandas as pd
import numpy as np
import warnings; warnings.filterwarnings('ignore')

movies = pd.read_csv('./tmdb_5000_movies.csv')

movies_df = movies[['id', 'genres', 'vote_average','title',
                    'vote_count', 'popularity', 'keywords', 'overview']]

movies_df[['genres','keywords']][:1]

from ast import literal_eval ## ast모듈은 문자를 가공해서 객체로 만들어줌!!!!! 
### literal_eval 함수는 자동으로 문자열을 파싱 해주는 역할 (to 객체)

movies_df['genres'] = movies_df['genres'].apply(literal_eval)
movies_df['keywords'] = movies_df['keywords'].apply(literal_eval)

movies_df['genres'] = movies_df['genres'].apply(lambda x : [y['name'] for y in x])
movies_df['keywords'] = movies_df['keywords'].apply(lambda x : [y['name'] for y in x])
movies_df


(4803, 20)


id                                         genres  vote_average  \
0      19995  [Action, Adventure, Fantasy, Science Fiction]           7.2   
1        285                   [Adventure, Fantasy, Action]           6.9   
2     206647                     [Action, Adventure, Crime]           6.3   
3      49026               [Action, Crime, Drama, Thriller]           7.6   
4      49529           [Action, Adventure, Science Fiction]           6.1   
...      ...                                            ...           ...   
4798    9367                      [Action, Crime, Thriller]           6.6   
4799   72766                              [Comedy, Romance]           5.9   
4800  231617             [Comedy, Drama, Romance, TV Movie]           7.0   
4801  126186                                             []           5.7   
4802   25975                                  [Documentary]           6.3   

                                         title  vote_count  popularity  \
0                                       Avatar       11800  150.437577   
1     Pirates of the Caribbean: At World's End        4500  139.082615   
2                                      Spectre        4466  107.376788   
3                        The Dark Knight Rises        9106  112.312950   
4                                  John Carter        2124   43.926995   
...                                        ...         ...         ...   
4798                               El Mariachi         238   14.269792   
4799                                 Newlyweds           5    0.642552   
4800                 Signed, Sealed, Delivered           6    1.444476   
4801                          Shanghai Calling           7    0.857008   
4802                         My Date with Drew          16    1.929883   

                                               keywords  \
0     [culture clash, future, space war, space colon...   
1     [ocean, drug abuse, exotic island, east india ...   
2     [spy, based on novel, secret agent, sequel, mi...   
3     [dc comics, crime fighter, terrorist, secret i...   
4     [based on novel, mars, medallion, space travel...   
...                                                 ...   
4798  [united states–mexico barrier, legs, arms, pap...   
4799                                                 []   
4800  [date, love at first sight, narration, investi...   
4801                                                 []   
4802          [obsession, camcorder, crush, dream girl]   

                                               overview  
0     In the 22nd century, a paraplegic Marine is di...  
1     Captain Barbossa, long believed to be dead, ha...  
2     A cryptic message from Bond’s past sends him o...  
3     Following the death of District Attorney Harve...  
4     John Carter is a war-weary, former military ca...  
...                                                 ...  
4798  El Mariachi just wants to play his guitar and ...  
4799  A newlywed couple's honeymoon is upended by th...  
4800  "Signed, Sealed, Delivered" introduces a dedic...  
4801  When ambitious New York attorney Sam is sent t...  
4802  Ever since the second grade when he first saw ...  

[4803 rows x 8 columns]

In [241]:
2. Vectorization

저희가 지난 NLP시간에 배웠던 Vectorize 기억나시나요? 
One-Hot Encoding, Embedding 등, 텍스트를 의미를 가지는 벡터로 만들기
위한 다양한 방법들이 있었습니다. 이번 데이터에서는 장르를 기반으로 할 것이기 때문에,
복습겸 NLP 때 배웠던 CountVectorizer로 Text Vectorization을 진행하겠습니다. 
Tfidf로 하지 않는 이유는 텍스트의 종류가 딱히 많지 않기 때문이죠 (만약 리뷰를 기반으로 했었으면
Tfidf로 했을 겁니다)


SyntaxError: invalid syntax (3759332552.py, line 1)

In [243]:
from sklearn.feature_extraction.text import CountVectorizer

## 영화의 장르마다 띄어쓰기로 구분한 새로운 column 생성
movies_df['genres_literal'] = movies_df['genres'].apply(lambda x : (' ').join(x))

## Vectorization 실행
count_vect = CountVectorizer(min_df = 0 , ngram_range=(1,2))
genre_mat = count_vect.fit_transform(movies_df['genres_literal'])



SyntaxError: invalid syntax (1528172205.py, line 10)

In [244]:
```
이렇게 하시면 기존의 DataFrame에 genres_literal 이라는 이름의 새로운 column이 추가되었습니다. 그 안의 내용은 우리가 의도하던 대로 genres list 내부의 요소들이 띄어쓰기로 구분되어있죠. 

이제 위에서 CountVectorizer로 구한 genre_mat 으로 Cosine Similarity를 구해보겠습니다.

(cosine Similarity는 기억나시죠? 두 벡터가 얼마나 비슷한 방향을 향하고 있는지를 통해 유사성을 측정하는 지표였죠!!)
```

SyntaxError: invalid syntax (1026022645.py, line 1)

In [245]:
# 3. Cosine Similarity 측정
from sklearn.metrics.pairwise import cosine_similarity

genre_sim = cosine_similarity(genre_mat, genre_mat)
print(genre_sim)

#1번째 원소는 본인-본인의 비교니까 당연히 1이고, 2번째 요소는 첫번째 행과 두번째 행과의
#cosine similarity,, 그 옆은 첫번째 행과 세번째 행과의 cosine smiliarity가 되겠죠? 

#즉, genre_sim 이라는 Matrix는 영화들끼리 비교를 해봤을 때,
#장르가 얼마나 유사한지를 나타낸 Matrix가 됩니다.


[[1.         0.59628479 0.4472136  ... 0.         0.         0.        ]
 [0.59628479 1.         0.4        ... 0.         0.         0.        ]
 [0.4472136  0.4        1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]


In [247]:
4. 기준에 의한 추천


이렇게 나온 애들을 sorting 해주기 위해서는 그냥 sort기능을 이용해도 되지만, 
저희는 이걸 가지고 좀 더 다양한 것들을 진행하기 위해 sort가 되게하는 index를 구할겁니다.
그런 기능을 하게 해주는 것이 바로 numpy의 argsort()입니다.
a 라는 객체에 저장된 array 가 오름차순으로 정렬되려면 [0,1,2,3,4,5]가 돼야할 겁니다. 
argsort()는 [0,1,2,3,4,5]가 되게하는 원래 array (a) 의 index를 반환해줍니다.



즉, [0,1,2,3,4,5]가 되려면... [0]번째에 있는 애가 처음, [3]번째에 있는 애가 그 다음,
[1]번째에 있는 애가 그 다음.... 이런 식으로 [0,3,1,4,2]라는 index array를 반환해준다는 것이죠. 


저희는 cosine similarity가 높은 순서대로 영화를 추천해줄 예정이니, 오름차순 index가 아니라 
내림차순 index를 받는 것이 좋겠죠. argmax()[::-1]를 해주시면 그냥 거꾸로 뒤집어줍니다. 
오름차순이었던 것이 내림차순이 되죠. 다만 우리는 2차원 행렬를 다뤄야하므로, argsort[:,::-1]을 
해줍니다. 모든 행에 대해서 내림차순 정렬을 수행해주는 것이죠.
이렇게 정렬된 index list도 구해냈으니, 이제 이걸 바탕으로 어떻게 추천을 할까~ 를 고민하면 됩니다. 



근데 단순하게 cosine similarity 로만 추천을 해주면 문제점이 하나 발생합니다.
오직 장르가 얼마나 비슷하냐에 따라서만 추천을 해주기 때문에, 추천된 영화가 좋은 영화인지 아닌지
전혀 고려하지 않는다는 것입니다.

때문에 우리는 추가적인 요소를 한 가지 더 고려하고자 합니다. 바로 가중평점(Weighted Rating)이라는 
요소입니다. 가중평점 식은 다음과 같습니다. 
여기서 

V : Vote Count (투표 횟수)

M : 평점 부여를 위한 최소 투표 횟수

R : Vote Average (평균 평점) [개별 영화]

C : 전체 영화에 대한 평균 평점  [전체 영화]

저희는 함수를 하나 만들어서, 함수에 제목을 입력해주면 그 영화와 장르
Cosine Similarity가 높으면서 Weighted Rating도 함께 높은 순서대로 정렬하는 걸 구현해보겠습니다. 

SyntaxError: invalid syntax (1781334144.py, line 1)

In [248]:
from sklearn.metrics.pairwise import cosine_similarity

genre_sim = cosine_similarity(genre_mat, genre_mat)
print(genre_sim)
genre_sim_sorted_ind = genre_sim.argsort()[:,::-1] 
percentile = 0.6
m = movies['vote_count'].quantile(percentile) ## 전체에서 60%에 해당되는 수를 최소 투표 횟수로 지정
C = movies['vote_average'].mean() ## 전체 영화에 대한 평점

def weighted_vote_average(record) : 
    v = record['vote_count']    ## 들어온 DataFrame에 대해 투표 횟수로 객체 저장
    R = record['vote_average']  ## 들어온 DataFrame에 대해 개별 영화 평균
    
    return ( (v/(v+m))*R + ((m/m+v))*C )  ## 위의 수식을 Return

## 기존 DataFrame에 weigted_vote_average 칼럼을 추가해줌
movies_df['weighted_vote'] = movies.apply(weighted_vote_average, axis=1)
def find_sim_movie(df, sorted_ind, title_name, top_n = 10) :
    title_movie = df[df['title'] == title_name]
    title_index = title_movie.index.values ## 해당 영화의 index 반환
    
    ## 여기가 바로 argsort를 쓴 이유입니다!! 
    similar_indexes = sorted_ind[title_index, 1 : (top_n*2)] ## 해당 영화에서 가장 유사한 top_n*2개의 영화 추출 
                                                            ## 대신 자기 자신은 제외 !! 
    similar_indexes = similar_indexes.reshape(-1) ## 2차원으로 되어있으므로 1차원으로 바꿔줌 (한줄짜리로!!)
    
    ########## 이러면 similar_indexes 에는 후보군의 index가 담겨있음 ##########
    
    final_list = df.iloc[similar_indexes].sort_values('weighted_vote', ascending=False)[:top_n]
                ## Weighted Vote를 기준으로 내림차순 정렬하고 top_n 만큼만 가져옴 !! 
    return final_list
    
find_sim_movie(movies_df, genre_sim_sorted_ind, 'Avatar', 5)


[[1.         0.59628479 0.4472136  ... 0.         0.         0.        ]
 [0.59628479 1.         0.4        ... 0.         0.         0.        ]
 [0.4472136  0.4        1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]


id                                         genres  vote_average  \
14    49521  [Action, Adventure, Fantasy, Science Fiction]           6.5   
46   127585  [Action, Adventure, Fantasy, Science Fiction]           7.5   
419    8247          [Adventure, Fantasy, Science Fiction]           5.9   
420   11253          [Adventure, Fantasy, Science Fiction]           6.5   
813    1924  [Action, Adventure, Fantasy, Science Fiction]           6.9   

                           title  vote_count  popularity  \
14                  Man of Steel        6359   99.398009   
46    X-Men: Days of Future Past        6032  118.078691   
419                       Jumper        1799   21.218000   
420  Hellboy II: The Golden Army        1527   58.579760   
813                     Superman        1022   48.507081   

                                              keywords  \
14   [saving the world, dc comics, superhero, based...   
46   [1970s, mutant, time travel, marvel comic, bas...   
419  [adolescence, based on novel, loss of child, f...   
420  [auction, northern ireland, resignation, super...   
813  [saving the world, journalist, dc comics, crim...   

                                              overview  \
14   A young boy learns that he has extraordinary p...   
46   The ultimate X-Men ensemble fights a war for t...   
419  David Rice is a man who knows no boundaries, a...   
420  In this continuation to the adventure of the d...   
813  Mild-mannered Clark Kent works as a reporter a...   

                               genres_literal  weighted_vote  
14   Action Adventure Fantasy Science Fiction   38752.353527  
46   Action Adventure Fantasy Science Fiction   36761.137339  
419         Adventure Fantasy Science Fiction   10970.801901  
420         Adventure Fantasy Science Fiction    9314.069800  
813  Action Adventure Fantasy Science Fiction    6237.356726

In [279]:
최근접 이웃 협업 필터링 추천 시스템

(Collaborative Filtering Recommend System)

최근접 이웃 협업 필터링의 예시는 여러분이 어떻게 보면 제일 익숙하실 겁니다. 
쿠팡같은 온라인 쇼핑물에 들어가서 상품을 볼 때, 다음과 같은 문구를 한 번 쯤은 보신 적이 있죠?


"이 상품을 고른 사람은 다음과 같은 상품도 구매했습니다." 

"당신과 비슷한 사람들은 다음과 같은 상품을 구매했습니다."


이렇듯, 나와 비슷한 사람들이, 혹은 내가 고른 아이템과 비슷한 다른 상품이 뭔지를 보면서 추천을 하는 시슽템이 바로 최근접 이웃 협업 필터링입니다. 이해하기 쉽게 비유를 하자면 

새로 개봉한 영화를 보기 전에, 나와 취향이 비슷한 친구에게 영화가 어땠냐고 물어보는 것과 같죠. 

취향이 비슷한 만큼, 그 영화에 대한 평가가 비슷할 테니까요.


위에 예시로 들어드린 문장은 각각 다음의 기술을 의미합니다.


1. 이 상품을 고른 사람은 다음과 같은 상품도 구매했습니다.   →  아이템 기반(Item-Item)

2. 당신과 비슷한 사람들은 다음과 같은 상품도 구매했습니다. → 사용자 기반(User-User) 


각각이 어떤 방식을 이용하는지 살펴본 다음에 실습도 진행해보겠습니다.

사용자 기반 최근접 이웃 방식

사용자 기반은 말 그대로 나와 비슷한 사람은 이 상품에 대해 어떻게 평가했는가? 를 참고한 겁니다.


내가 고르지 않은 상품에 대해 나와 물품 구매 취향이 비슷한 B라는 사람이 이미 골랐다면
B가 어떻게 그 상품을 평가했는지를 보고 마음에 들어할지 안 들어할지 예측한다는 것이죠.


쉽게 그림으로 설명드리면
A 부터 D라는 사람이 있고, 3대 측정 종목인 벤치, 데드, 스쿼트가 있다고 해봅시다.

이 3개의 운동에 대해 4명이 메긴 점수를 나타낸 Matrix입니다. (애초에 이렇게 표로
                                        나타내는 작업부터 해야합니다 ㅋㅋ)

​
자, 그럼 이제 ? 에 뭐가 와야할 지 예측해야하는 과제가 주어졌는데, 여러분들
같으면 어떻게 할 것같은가요?

대충 표를 봤을 때, 

A와 B는 상체 운동 위주를 좋아하는 것 같네요( 데드는 전신이지만 뭐 루마니안이라고 해봅시다 ) 
. A와 비슷한 운동 취향을 가진 B가 하체 운동인 스쿼트의 점수를 매우 낮게 평가했습니다. 
하체가 힘들다고는 하지만 좀 너무하네요 ㅠ ㅋㅋㅋㅋ 아무튼 A와 비슷한 취향의 B가 스쿼트의
점수를 낮게 줬으니, A도 스쿼트에 대해 낮은 점수를 줄 것이라고 예측합니다.



이번엔 D를 채워볼까요? C와 D는 A,B와는 다르게 스쿼트를 진짜 좋아하는 모습을 보입니다. 
이와 비슷한 취향을 가지는 D도 C처럼 벤치프레스의 점수를 낮게 주었을 것이라고 예측하는 것이죠.

간단하죠? 이제 사용자 기반 최근점 이웃 방식에 대해 알아봤고,
아이템 기반은 어떻게 하는지 알아보겠습니다.


아이템 기반 최근접 이웃 방식

사실 아이템 기반도 사용자 기반과 비교해서 방식이 크게 다르진 않습니다. 
사용자는 비슷한 사용자가 뭘 좋아했냐고 보는 거고, 아이템 기반은 사용자들이 평가를 
비슷하게 내린 아이템을 추천하는 것이죠.


말만하면 어렵습니다. 한번 그림으로 쉽게 나타내보겠습니다.



아까와 다르게 이제 왼쪽에 종목이 들어왔고 column에 사용자가 들어왔죠? 
자, 이번엔 새로운 종목인 레그프레스가 들어왔습니다. 



위에서 아이템 기반은 아이템에 대한 사용자들의 평가의 분포를 보고 평점을 예측한다고 했습니다.
"어떤 상품을 좋아할까?"에 좀 더 초점을 맞췄다고 생각하시면 편합니다.

벤치프레스는 10,9,8 // 데드리프트는 10,8,10 // 스쿼트는 2,3,3 입니다.
그럼 레그프레스는 사용자 A가 좋아할까요? 아님 싫어할까요? ​

A는 아마 싫어할 것입니다. 아이템에 대한 평가가 비슷한 스쿼트와 비교해봤을 때,
스쿼트에 대해 낮은 점수를 부여했기 때문이죠. 따라서 적어도 A에게 레그프레스는 추천되지 않을 것입니다.


그럼 C는 데드리프트를 좋아할까요? C에게 종목을 추천해줄 수 있다면, 어떤 종목을 추천할 건가요? 


아이템들에 대한 평점 분포를 살펴봤을 때, C는 벤치프레스와 가장 평점 분포가 유사한 데드리프트를
좋아할 확률이 높습니다. 따라서 C에겐 스쿼트나 레그프레스를 추천하는 것이 아닌, 
데드리프트를 추천하게 되는 것이죠.



아이템 기반은 아이템이 가지는 특성이나 속성이 비슷한 걸 추천하는 것이 아닙니다.
그건 오히려 컨텐츠 기반에서 우리가 이미 다뤄봤죠. 아이템 기반은 위처럼 "아이템에 대한 평가 분포"가
비슷한 아이템을 추천하는 방식입니다. 헷갈리지 않게 조심하세요!! 


현업에선 사용자 기반보다 아이템 기반을 더 많이 사용한다고 합니다.
위의 행렬들은 대부분 Sparse Matrix로 나타나게 되는데, 사용자 기반으로 비교를 
하기엔 정보가 많이 부족해서 그런 것이라고 하네요. 비슷한 제품을 좋아한다고 해서 꼭
그 사람들의 취향이 꼭 비슷하다고 단정 지을 수도 없습니다. (아이폰만 구매한 사람들끼리 영화 
                                   취향까지 비슷할 수는 없겠죠)


실습을 진행하기 위해 새로운 데이터셋을 가져오겠습니다. 

사용자 기반이나 아이템 기반을 하기 위해서는 위에서 말씀 드린 대로

"유저 - 아이템 간의 행렬"이 필요합니다. 즉, 어떤 유저가 어떤 아이템에 대해 어떻게 
평가했는지에 대한 데이터가 필요합니다. 우리가 위에서 이미 진행했던 데이터셋은 장르에 
대한 전체적인 평가만 있기 때문에, 협업필터링에 적용하기엔 무리가 있습니다. 때문에 아래의
데이터셋으로 진행합니다. 


SyntaxError: invalid syntax (2810099874.py, line 1)

In [1]:
import pandas as pd
import numpy as np

movies = pd.read_csv('./movies.csv')
ratings = pd.read_csv('./ratings.csv')
movies.head()
ratings.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [2]:
data = np.array(np.arange(15)).reshape(3,5)
df = pd.DataFrame(data, index=['A','B','C'], columns=['경제','경영','데이터','컴공','철학'])
df

#먼저 데이터를 우리가 필요한 형식으로 맞춰주기 위해 pandas의 pivot_table을 활용합니다. 
#위의 예시로 가상의 DataFrame을 하나 형성하고 pivot_table을 이용해주면 아래와 같은 모양으로 바뀝니다.


경제  경영  데이터  컴공  철학
A   0   1    2   3   4
B   5   6    7   8   9
C  10  11   12  13  14

In [4]:
df.pivot_table('데이터', index='경제', columns='경영')
#pivot_table은 엑셀로 실무를 하시는 분들에겐 정말 많이 사용하시는 기능일 텐데요!
#column에 대해 다시 정렬해주고 싶을 때 매우 유용하게 사용됩니다.
#row의 값들을 column 레벨로 바꿀 수도 있죠. 
#그럼 pandas의 pivot_table을 이용해서 우리의 데이터를 한번 바꿔보겠습니다. 


경영   1    6     11
경제                
0   2.0  NaN   NaN
5   NaN  7.0   NaN
10  NaN  NaN  12.0

In [5]:
df.pivot_table('데이터', index='경제', columns='경영')



경영   1    6     11
경제                
0   2.0  NaN   NaN
5   NaN  7.0   NaN
10  NaN  NaN  12.0

In [6]:
pivot_table은 엑셀로 실무를 하시는 분들에겐 정말 많이 사용하시는 기능일 텐데요! 
column에 대해 다시 정렬해주고 싶을 때 매우 유용하게 사용됩니다. row의 값들을 column 
레벨로 바꿀 수도 있죠. 그럼 pandas의 pivot_table을 이용해서 우리의 데이터를 한번 바꿔보겠습니다. 


SyntaxError: invalid syntax (3824227497.py, line 1)

In [7]:
ratings = ratings[['userId', 'movieId','rating']] ## 필요한 것만 가져옴

## 피벗테이블 사용
ratings_matrix = ratings.pivot_table('rating', index='userId', columns='movieId')
ratings_matrix.head()


movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     NaN     4.0     NaN     NaN     4.0     NaN     NaN   
2           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5           4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  9       10      ...  193565  193567  193571  193573  193579  193581  \
userId                   ...                                                   
1           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
5           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  193583  193585  193587  193609  
userId                                   
1           NaN     NaN     NaN     NaN  
2           NaN     NaN     NaN     NaN  
3           NaN     NaN     NaN     NaN  
4           NaN     NaN     NaN     NaN  
5           NaN     NaN     NaN     NaN  

[5 rows x 9724 columns]

In [8]:

그럼 위와 같은 column을 얻을 수 있습니다. 근데 이렇게 하면 UserId가 index로 와있고 
아이템들이 column으로 와있습니다. 이 둘의 위치는 transpose로 쉽게 바꾸면 되지만,
일단 영화 Id가 보기 힘드니 이를 영화제목으로 바꾸겠습니다. 간단합니다 .


SyntaxError: invalid syntax (923999877.py, line 1)

In [9]:
## movie id 를 표시하기 위해 다른 DF 를 가져옴
rating_movies = pd.merge(ratings, movies, on='movieId')

## 새로운 df로 pivot_table
ratings_matrix = rating_movies.pivot_table('rating', index='userId', columns='title')

## transpose()를 이용하여 index에 아이템, column에 user가 오게 만듦
ratings_matrix_T = ratings_matrix.transpose()

## NaN값이 있으면 곤란하므로 평가를 아직 하지 않았다는 의미에서 NaN을 0으로 바꿈
ratings_matrix_T.fillna(0, inplace=True)
ratings_matrix_T.head()

userId                                   1    2    3    4    5    6    7    \
title                                                                        
'71 (2014)                               0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Round Midnight (1986)                   0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Salem's Lot (2004)                      0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Til There Was You (1997)                0.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId                                   8    9    10   ...  601  602  603  \
title                                                   ...                  
'71 (2014)                               0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Round Midnight (1986)                   0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Salem's Lot (2004)                      0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Til There Was You (1997)                0.0  0.0  0.0  ...  0.0  0.0  0.0   

userId                                   604  605  606  607  608  609  610  
title                                                                       
'71 (2014)                               0.0  0.0  0.0  0.0  0.0  0.0  4.0  
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Round Midnight (1986)                   0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Salem's Lot (2004)                      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Til There Was You (1997)                0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 610 columns]

In [10]:
간단하죠? 이제 우리가 원하는 방식대로 데이터를 준비 완료했습니다.


자, 아까 위에서 아이템 기반 방식은 평점 분포가 비슷한 아이템을 기준으로 추천을 한다고 했습니다.
그럼 이 평점 분포가 비슷하다는 것을 어떻게 컴퓨터에게 인식시킬 수 있을까요? 네.. 맞습니다. 
여기서 바로 Cosine Similarity를 사용합니다!


Cosine Similarity는 Text에만 사용할 수 있는 것이 아닙니다. 벡터로만 나타낼 수 있다면 
뭐든지 그 유사도를 측정할 수 있죠. 


위의 DataFrame을 가지고 Cosine Similarity를 측정해보겠습니다. (많이해서 익숙하시죠?)


SyntaxError: invalid syntax (1029315420.py, line 1)

In [11]:
from sklearn.metrics.pairwise import cosine_similarity
## cosine 유사도 구하기
item_sim = cosine_similarity(ratings_matrix_T, ratings_matrix_T)

## 이걸 DF로 만들기
item_sim_df = pd.DataFrame(item_sim , index=ratings_matrix.columns, columns = ratings_matrix.columns)
item_sim_df.head()


title                                    '71 (2014)  \
title                                                 
'71 (2014)                                      1.0   
'Hellboy': The Seeds of Creation (2004)         0.0   
'Round Midnight (1986)                          0.0   
'Salem's Lot (2004)                             0.0   
'Til There Was You (1997)                       0.0   

title                                    'Hellboy': The Seeds of Creation (2004)  \
title                                                                              
'71 (2014)                                                              0.000000   
'Hellboy': The Seeds of Creation (2004)                                 1.000000   
'Round Midnight (1986)                                                  0.707107   
'Salem's Lot (2004)                                                     0.000000   
'Til There Was You (1997)                                               0.000000   

title                                    'Round Midnight (1986)  \
title                                                             
'71 (2014)                                             0.000000   
'Hellboy': The Seeds of Creation (2004)                0.707107   
'Round Midnight (1986)                                 1.000000   
'Salem's Lot (2004)                                    0.000000   
'Til There Was You (1997)                              0.000000   

title                                    'Salem's Lot (2004)  \
title                                                          
'71 (2014)                                          0.000000   
'Hellboy': The Seeds of Creation (2004)             0.000000   
'Round Midnight (1986)                              0.000000   
'Salem's Lot (2004)                                 1.000000   
'Til There Was You (1997)                           0.857493   

title                                    'Til There Was You (1997)  \
title                                                                
'71 (2014)                                                0.000000   
'Hellboy': The Seeds of Creation (2004)                   0.000000   
'Round Midnight (1986)                                    0.000000   
'Salem's Lot (2004)                                       0.857493   
'Til There Was You (1997)                                 1.000000   

title                                    'Tis the Season for Love (2015)  \
title                                                                      
'71 (2014)                                                           0.0   
'Hellboy': The Seeds of Creation (2004)                              0.0   
'Round Midnight (1986)                                               0.0   
'Salem's Lot (2004)                                                  0.0   
'Til There Was You (1997)                                            0.0   

title                                    'burbs, The (1989)  \
title                                                         
'71 (2014)                                         0.000000   
'Hellboy': The Seeds of Creation (2004)            0.000000   
'Round Midnight (1986)                             0.176777   
'Salem's Lot (2004)                                0.000000   
'Til There Was You (1997)                          0.000000   

title                                    'night Mother (1986)  \
title                                                           
'71 (2014)                                                0.0   
'Hellboy': The Seeds of Creation (2004)                   0.0   
'Round Midnight (1986)                                    0.0   
'Salem's Lot (2004)                                       0.0   
'Til There Was You (1997)                                 0.0   

title                                    (500) Days of Summer (2009)  \
title                                                                  
'71 (2014)                              

In [12]:
그럼 이렇게 나온 DataFrame은 아이템들 간의 "평점"이 얼마나 유사한지를 측정한 게 됩니다. 
이제 이걸 기반으로 유사도가 높은 순서대로 sorting을 해주면 되겠죠? 


Round Midnight 이라는 영화와 가장 아이템 평점 분포가 유사한 상위 10개를 가져오겠습니다.
(본인을 제외하니 1:11로 하겠습니다)


SyntaxError: invalid syntax (378402759.py, line 1)

In [13]:
item_sim_df["'Round Midnight (1986)"].sort_values(ascending=False)[1:11]


title
Allegro non troppo (1977)                                  0.707107
American Friend, The (Amerikanische Freund, Der) (1977)    0.707107
And Starring Pancho Villa as Himself (2003)                0.707107
10th Victim, The (La decima vittima) (1965)                0.707107
20 Million Miles to Earth (1957)                           0.707107
American Grindhouse (2010)                                 0.707107
Attack of the Puppet People (1958)                         0.707107
Asphyx, The (1973)                                         0.707107
Agony and the Ecstasy, The (1965)                          0.707107
7 Faces of Dr. Lao (1964)                                  0.707107
Name: 'Round Midnight (1986), dtype: float64

In [14]:
네 그럼, 이렇게 해당 영화와 평점분포가 비슷하다고 할 수 있는 10개의 영화들을 나열할 수 있는 것이죠.
이중에서 아무거나 하나 골라서 추천하면 높은 확률로 만족하겠죠?



근데 이러면 단점이 하나 있습니다. 우리가 지금까지 구현한 것은

 "이 영화의 평점은 그 영화와 비슷합니다! 그거 좋아하시면 이것도 좋아하실듯 ㅎㅎ" 이러는 건데,
    문제는 개인의 취향을 여기에 반영할 수가 없습니다. A라는 사람에게 맞춤형 아이템 기반 필터링 
    추천시스템을 통해 영화를 추천해주려면 어떻게 해야할까요? 사실 뒤에 Surprise라는 패키지를 이용하면
... 다 되는 거지만, 일단 알아가봅시다!


지금부터 말씀드릴 수식이 꽤나 복잡해 보일 수 있지만 
그 의미를 하나하나 살펴보시면 그다지 어렵지는 않습니다.


SyntaxError: invalid syntax (4065988696.py, line 1)

In [15]:
사용자 u의 아이템 i에 대한 예측 평점 값

Si,N
아이템 i와 가장 유사도가 높은 N개의 아이템 유사도 Vector (Cosine Similarity!!)

R_{u,N}
사용자 u의 아이템 i와 가장 유사도가 높은 N개의 아이템에 대한 실제 평점 (Real Rating)

{S}_{i,N}
그냥 정규화를 위해 나눠줌 (0~1 사이의 값으로 만들기 위해)


위의 요소들을 가지고 식을 다시 보면, 결국 실제로 주어진 Rating에 아이템 유사도라는 
가중치를 부여한 것입니다. (행렬끼리의 곱이니 내적을 해야겠죠?) 그렇게 하면,
실제로 부여한 Rating에 대해 유사도에 의한 영향력을 부여할 수 있습니다. 

즉, 이렇게 나온 결과들을 활용해 개인의 취향까지 반영한 유사도를 기반으로 추천을 할 수 있다는 것이죠.


사실 강의를 진행하면서 해당 코드를 돌려봤는데.... 제 컴퓨터로는 30분이 지나도 안 되더군요 ㅠㅠ 
뭐가 이렇게 많이 걸리는지....
때문에 실습은 어려울 것같고, 위의 수식을 함수로 옮겨 적은 것과 어떻게 반환하는지
코드만 적어두도록 하겠습니다.


SyntaxError: invalid syntax (2170800048.py, line 1)

In [16]:
def predict_rating(ratings_arr, item_sim_arr) :
    ratings_pred = ratings_arr.dot(item_sim_arr)
    np.array([np.abs(item_sim_arr).sum(axis=1)])
    return ratings_pred


In [17]:
잠재 요인 협업 필터링 추천 시스템

(Latent Factor Collaborative Filtering Recommend System)
최근 들어 가장 많이 쓰이고 있는 방법이 바로 잠재 요인 협업 필터링 추천 시스템입니다.
넷플릭스가 이 방식을 사용하게 되면서 다른 기업들도 해당 방법을 사용중이죠. 



해당 기법의 가장 핵심이 되는 잠재요인(Latent Factor)이라는 단어가 굉장히 익숙하지 않나요?
차원축소 파트를 한번쯤 읽어보신 분들은 아~ 그거~ 하시면서 SVD나 NMF라는
단어를 기억하실 수 있으실 겁니다. 

혹시 기억 안 나시는 분들은 아래의 포스팅에 다녀오셔도 될 거같습니다 ㅎㅎ 
요약하자면, 우리가 인수분해를 하듯이, 하나의 큰 행렬을 여러 개의 작은 행렬들로 표현할 수 있는 방법이었습니다.

작은 행렬들로 표현하는 과정에서, 기존에 없던 새로운 column이나 row적 요소가 나오는데,
그걸 바로 Latent Factor, 잠재요인이라고 했죠. 



이 잠재 요인을 적극적으로 활용한 것이 바로 이번에 알아볼 Latent Factor 기반 추천시스템입니다.


저희가 이제 할 거를 그림으로 미리 설명을 드리면 다음과 같습니다.
이런식으로 왼쪽에 있는 Sparse Matrix인 원본 행렬을 가지고 오른쪽의 2개 이상의 Dense Matrix로 분해하는 겁니다. 이런 과정에서 Factor라는 새로운 요소가 나왔는데, 이 새롭게 나온 요소를 Latent Factor라고 하고, 

이 Latent Factor를 가지고 원본 행렬을 재 구성합니다.


재구성하는 방법은 두 밀집 행렬을 말 그대로 내적시켜주면 되고, 
이렇게 내적한 결과로, 원본 행렬에서 비어있는 부분을 예측하는 것이죠. 
굉장히 직관적이면서 굉장히 강력하죠? 



자, 근데 여기서 문제가 발생합니다. Sparse Matrix를 분해시킨다고 했는데,
NaN값이 많은 기존의 원본 행렬을 분해할 수가 있을까요?

네, 없습니다. 때문에, 우리는 Boosting 알고리즘 시간에 배운 정말 강력한 기법인
SGD를 이용하여 빈 칸을 채워준 다음에 SVD를 진행하도록 하겠습니다. 


혹시 SGD가 기억 안 나시는 분은 아래의 또 제 포스팅을 다녀오시면 좋을 거 같습니당 ㅎㅎ
경사하강법이라는 제목으로 소개시켜드렸습니다.
방법은 아래와 같습니다.



1. 원본의 Sparse Matrix를 Dense로 만들기 위해 임의의 두 행렬 P와 Q로 분해시킴.

2. 임의의 값이 채워진 P와 Q를 내적시키면 원본 행렬과 같은 크기의 예측 행렬이 나오는데,

    이 예측 행렬과 원본 행렬의 차이(MSE)가 낮게 나오는 방향으로 P와 Q의 크기를 업데이트 시킴.

3. 2번의 방법을 바로 SGD라고 함. 

4. MSE를 구하는 방법은, 원본 행렬에서 값이 있는 index와 예측 행렬의 해당 index의 Error을 비교함.


한번 코드로 어떻게 구현하는지 살펴보겠습니다. 


SyntaxError: invalid syntax (1302047121.py, line 1)

In [19]:
import numpy as np
## 원본행렬 (Sparse) 생성
R = np.array([[4, np.NaN, np.NaN, 2, np.NaN ],
              [np.NaN, 5, np.NaN, 3, 1 ],
              [np.NaN, np.NaN, 3, 4, 4 ],
              [5, 2, 1, 2, np.NaN ]])

num_users, num_items = R.shape

## 잠재 요인의 수는 3으로 설정. K는 Hyper Parameter이므로 나중에 Grid로 찾기도 함.
K=3

## 두 개의 행렬로 분해한다고 가정. 정규분포를 가진 Random하게 값을 입력해줌 !! 
np.random.seed(1)
P = np.random.normal(scale=1./K, size=(num_users, K))
Q = np.random.normal(scale=1./K, size=(num_items, K))
print("P:",P)
print("Q:",Q)


P: [[ 0.54144845 -0.2039188  -0.17605725]
 [-0.35765621  0.28846921 -0.76717957]
 [ 0.58160392 -0.25373563  0.10634637]
 [-0.08312346  0.48736931 -0.68671357]]
Q: [[-0.1074724  -0.12801812  0.37792315]
 [-0.36663042 -0.05747607 -0.29261947]
 [ 0.01407125  0.19427174 -0.36687306]
 [ 0.38157457  0.30053024  0.16749811]
 [ 0.30028532 -0.22790929 -0.04096341]]


In [20]:
R

array([[ 4., nan, nan,  2., nan],
       [nan,  5., nan,  3.,  1.],
       [nan, nan,  3.,  4.,  4.],
       [ 5.,  2.,  1.,  2., nan]])

In [ ]:

자, 왼쪽의 원본 행렬을 오른쪽의 P와 Q로 분해한 가장 초기의 모습입니다. 
여기서 P와 Q의 값은 SGD를 통해 원본행렬과의 차이를 줄여나가는 방향으로 업데이트를 해나갈겁니다.
한번 P와 Q를 내적해볼까요?

물론 그냥 이렇게 하면 shape이 맞지 않아 내적을 하지 못하므로 Q를 Transpose 시켜주겠습니다. 


In [21]:
print('초기 내적 값 P*Q: \n', np.dot(P,Q.T))


초기 내적 값 P*Q: 
 [[-9.86215743e-02 -1.35273244e-01  3.25938576e-02  1.15829937e-01
   2.16275915e-01]
 [-2.88426030e-01  3.39039250e-01  3.32466259e-01 -1.78279922e-01
  -1.41717429e-01]
 [ 1.01671414e-02 -2.29768982e-01 -8.01253853e-02  1.63482851e-01
   2.28119515e-01]
 [-3.12983578e-01  2.03409279e-01  3.45449141e-01 -2.71808518e-04
  -1.07906618e-01]]


In [22]:

원본 행렬과 똑같은 4x5 행렬이 나왔습니다. 지금은 원본 행렬의 같은 위치에 있는 값과 비교해봤을 때,
정말 터무니 없는 Error가 나오지만, 이를 SGD로 업데이트 하면서 어떻게 변하는지 살펴보겠습니다.
일단 Error를 우리가 하나하나 계산할 수 없으니, 이를 수행해줄 함수를 하나 만들어야겠죠



SyntaxError: invalid syntax (2870295591.py, line 1)

In [23]:
Surprise 패키지

물론 이렇게 유용한 추천시스템은 이미 파이썬에 패키지로 마련되어 있습니다.
심지어 sklearn에 익숙한 사용자들을 위해 매소드의 이름도 sklearn과 상당히 비슷하게 되어있습니다 ..


그럼 지금까지 우리가 위에서 배웠던 건 다 쓸모가 없느냐?! 그렇지는 않죠. 
계속 프로젝트를 하면서 느끼는 것이, 모델의 원리를 이해하지 않고 사용만 하다보면
분명히 막히는 지점이 온다는 거였습니다. 모델마다 분명히 적절하게 쓰이는 상황과 쓰여서는 
안 되는 상황이 있는데, 그걸 무시하고 써버릴 수도 있다는 것이죠. 때론 내가 무시했던 모델이
결과가 더 잘 나오는 경우도 많았습니다. 



하지만 뭐 일단 원리는 원리! 실무는 실무겠죠? Surprise 패키지는 어떻게 우리에게 놀라운
추천시스템 방법을 보여줄지 한번 살펴봅시다. 실제로 자주 쓰는 것들만요!


아까 저희가 사용했던 rating 데이터 셋트를 한번 보시겠습니다. 
Suprise는 DataFrame으로 된 데이터를 읽을 때, 반드시 지켜줘야 하는 룰이 있습니다. 
읽어오는 column의 순서가 반드시

User / Item / Rating 순서로 이루어져야 한다는 것입니다.  이걸 Reader라는 
함수로 알려주면서 불러오는 방법이 있고, 애초에 DataFrame을 새로 저 순서대로 구성하는 방법이 있죠.
한번 위의 ratings 파일을 이용해서 살펴보시겠습니다. 


SyntaxError: invalid syntax (221701135.py, line 1)

In [24]:
import pandas as pd
from surprise import Reader, Dataset, SVD, accuracy
from surprise.model_selection import train_test_split

ratings = pd.read_csv('./ratings.csv')
## Reader를 통해 데이터를 읽어올 방식을 정의함
reader = Reader(rating_scale = (0.5,5.0)) ## 평점이 0.5~5.0 사이의 값이라는 얘기!!

## DataFrame을 그대로 바로 읽어올 수는 없고, Dataset의 load_from_df 함수를 이용해서 불러와야함
## 다만 요구되는 순서에 맞게 df를 바꿔준 다음에 불러옴
data = Dataset.load_from_df(ratings[['userId','movieId','rating']], reader)

## surprise는 추가로 sklearn과 비슷하게 train_test_split 기능을 제공함 똑같음!! 
trainset, testset = train_test_split(data, test_size=0.25)

## 어떤 방식으로 추천시스템을 구현할 지 정할 수 있음.
## 바로 위에서 배웠던 SVD기반 행렬분해 잠재요인으로 한번 해보겠음 ! 
model = SVD(n_epochs=50, n_factors=50) ## 잠재요인을 50개로 설정
model.fit(trainset)

## 예측함에 있어서는 2가지로 나뉨.

# 전체 데이터 세트에 대해서 추천을 예측할 때 : test
test_preds = model.test(testset)

# 개별 유저에 대해 평점을 예측할 때 : predict
## 단, user와 item 은 str로 입력되어야함. 
## 물론 아직 user가 해당 item에 대해 평가를 내리지 않아야겟쥬?
predict_preds = model.predict(str(196), str(302))

## 결과보기
print('전체 데이터 예측에 대한 rmse \n',accuracy.rmse(test_preds))
print('+++'*30)
print('196번 User에 대한 예측 평점 : ', predict_preds[3])

RMSE: 0.8888
전체 데이터 예측에 대한 rmse 
 0.8888014616965529
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
196번 User에 대한 예측 평점 :  3.5052163909714786


In [31]:
predict_preds

Prediction(uid='196', iid='302', r_ui=None, est=3.5052163909714786, details={'was_impossible': False})

In [32]:
test_preds

[Prediction(uid=109, iid=32, r_ui=4.0, est=3.7199949002206942, details={'was_impossible': False}),
 Prediction(uid=249, iid=64716, r_ui=4.0, est=4.132323759935337, details={'was_impossible': False}),
 Prediction(uid=177, iid=93008, r_ui=5.0, est=3.257777168797843, details={'was_impossible': False}),
 Prediction(uid=480, iid=37741, r_ui=4.5, est=3.2744459506231536, details={'was_impossible': False}),
 Prediction(uid=563, iid=61250, r_ui=1.5, est=2.9382969323588535, details={'was_impossible': False}),
 Prediction(uid=365, iid=54503, r_ui=3.5, est=3.5925134727513433, details={'was_impossible': False}),
 Prediction(uid=47, iid=8533, r_ui=3.5, est=3.0218778325060067, details={'was_impossible': False}),
 Prediction(uid=534, iid=46335, r_ui=3.0, est=3.351429655229343, details={'was_impossible': False}),
 Prediction(uid=6, iid=185, r_ui=3.0, est=3.4670575574563713, details={'was_impossible': False}),
 Prediction(uid=438, iid=1831, r_ui=3.0, est=2.9385492578585746, details={'was_impossible': Fa

In [25]:
각 코드에 대한 설명은 주석으로 달아놨으니 참고하시면 되겠습니다. 

주의하실 점은 전체 데이터에 대해 예측할 때 사용하는 test()와

개별 유저의 평점을 예측할 때 사용하는 predict() 를 각각 다를 때 사용해야 한다는 것과

predict()를 사용하실 때는 입력되는 dtype이 str로 이루어져야 한다는 점만 주의하시면 되겠습니다. 



상당히 직관적이고, 코드들이 sklearn과 비슷해서 처음 사용하시더라도 쉽게 하실 수 있습니다. 


하나하나 구현하는 것보다는... surprise를 통해 쉽게쉽게.. ㅎㅎ 할 수 있다는 게 참.. 좋죠? ㅎㅎ 


surprise는 놀랍게도 cross_validation과  GridSearchCV도 제공합니다. 사실 추천시스템에서 
할 게 잠재요인과 epoch를 조절하는 것밖에 없지만 그것마저 하나하나 하기엔 너무 귀찮으니
, 간단하게 사용법만 알고 넘어가도록 하겠습니다. 


SyntaxError: invalid syntax (4266409236.py, line 1)

In [37]:
import pandas as pd
from surprise import Reader, Dataset, SVD, accuracy
from surprise.model_selection import train_test_split

ratings = pd.read_csv('./ratings.csv')
reader = Reader(rating_scale = (0.5,5.0)) 
data = Dataset.load_from_df(ratings[['userId','movieId','rating']], reader)
trainset, testset = train_test_split(data, test_size=0.25)
model = SVD(n_epochs=50, n_factors=50)

# 1.위 코드를 활용하여 사용자 아이디 196번이 예측한 아이템 아이디 302번의 예측평점을 구해주세요.
model.fit(trainset)
predict_preds = model.predict(str(196), str(302))
predict_preds[3]

3.5037552725878323

In [36]:
# 2. 위의 코드를 활용하여 전체 데이터 예측에 대한 rmse를 구해주세요.

model.fit(trainset)
test_preds = model.test(testset)
accuracy.rmse(test_preds)

RMSE: 0.8839


0.8838975821376198

In [39]:
text = 'I decided, very early on, just to accept life unconditionally.I never expected it to do anything special for me, yet I seemed to accomplish far more than I had ever hoped. Most of the time it just happened to me withoutmy ever seeking it.'
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# 3. 위의 텍스트의 감성 점수를 구해주세요


vader_analyzer = SentimentIntensityAnalyzer()
senti_score = vader_analyzer.polarity_scores(text)

print(senti_score)

{'neg': 0.0, 'neu': 0.776, 'pos': 0.224, 'compound': 0.8658}


In [1]:
import pandas as pd
from surprise import Reader, Dataset, SVD, accuracy
from surprise.model_selection import train_test_split

ratings = pd.read_csv('./ratings.csv')
reader = Reader(rating_scale = (0.5,5.0)) 
data = Dataset.load_from_df(ratings[['userId','movieId','rating']], reader)
trainset, testset = train_test_split(data, test_size=0.25)
model = SVD(n_epochs=50, n_factors=50)

In [ ]:
model.test(trainset)