# 정리

In [ ]:
iris_df['label']=iris_df['label'].map({0:'setosa', 1:'versicolor', 2: 'virginica'})
검증은 test x랑 y 한번씩 대응하고 학습함

교차검증은 1234를 테스트셋 잡고 5를 검증하고 1245하고 3검증 1345하고 2검증 5번검증
from sklearn.model_selection import KFold
kfold=KFold(n_splits=5)
for train_index,test_index in kfold.split(iris_data): # 인덱스 반환 
     print(train_index,test_index) # 트레인 인덱스와 테스트 인덱스를 쪼갠게 5개 있음 
        # 120개 30개로 쪼갬 iris_data의 인덱스를 120 30으로
        # 인덱스를 하는 이유는 트레이닝에서 2열심히 해도 test에 2가없으면 무용지물
        # 150개중 012가 0은 100개 1은 40개 2는 10개 편중된 데이터라면
        # train과 test에 골고루 분류된어야함 
        #stratified 계층, 층화 전체에서 비율에 맞게 뽐음 
        
iris = load_iris()                   # 파일부르기

iris_data = iris.data
                # data(정보)와 target(매치대상) 저장
iris_label= iris.target


dt_clf = DecisionTreeClassifier()      # 의사결정 트리 
kfold = KFold(n_splits=5)

cv_accuracy = []

# KFold객체의 split( ) 호출하면 폴드 별 학습용, 검증용 테스트의 인덱스를 반환한다. 이거 중요함.  
for train_index, test_index  in kfold.split(iris_data): 
    
    # print(train_index, test_index)
    # print("---"*10)
    # kfold.split( )으로 반환된 인덱스를 이용하여 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = iris_data[train_index], iris_data[test_index]
    y_train, y_test = iris_label[train_index], iris_label[test_index]

    
    dt_clf.fit(X_train , y_train)    
    pred = dt_clf.predict(X_test)
    
   
    accuracy = accuracy_score(y_test,pred)   
    cv_accuracy.append(accuracy)
 
    print("개별 검증 정확도: ", cv_accuracy)
    
print('평균 검증 정확도:', np.mean(cv_accuracy))        

In [1]:
스카 사물함 연장 

In [4]:
ml 알고리즘은 결손값이있으면 x 숫자열 문자열 가능?
기본적으로 숫자열 문자열 안됨 

지도학습은 학습을 위한 다양한 피처(Y)와 분류 결정 레이블(X)데이터로 모델을 학습한다.
x
분류는 답이 정해져있고 군집화는 답이 정해져 있지 않다. 
o

사이킷런에서 분류알고리즘을 구현하는 클래스 Classfier 
사이컷런에서 회귀알고리즘을 ~~  Regressor
위 두클래스를 합쳐서 지도학습의 모둔 알고리즘을 구현한 클래스 Estimator
사이킷런의 머신러닝 알고리즘은 문자열 값을 입력값으로 허용하지 않지만 nan, null 값은
허용된다. x 



SyntaxError: invalid syntax (3050028489.py, line 2)

In [7]:
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [8]:
arr = np.array(['TV', '냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']*10) 
arr

array(['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서', 'TV', '냉장고',
       '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서', 'TV', '냉장고', '전자레인지',
       '컴퓨터', '선풍기', '선풍기', '믹서', '믹서', 'TV', '냉장고', '전자레인지', '컴퓨터',
       '선풍기', '선풍기', '믹서', '믹서', 'TV', '냉장고', '전자레인지', '컴퓨터', '선풍기',
       '선풍기', '믹서', '믹서', 'TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서',
       '믹서', 'TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서', 'TV',
       '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서', 'TV', '냉장고',
       '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서', 'TV', '냉장고', '전자레인지',
       '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'], dtype='<U5')

In [9]:
encoder =LabelEncoder()
encoder.fit(arr)
labels =encoder fit arr

In [12]:
labels=encoder.fit_transform(arr)
labels

array([0, 1, 4, 5, 3, 3, 2, 2, 0, 1, 4, 5, 3, 3, 2, 2, 0, 1, 4, 5, 3, 3,
       2, 2, 0, 1, 4, 5, 3, 3, 2, 2, 0, 1, 4, 5, 3, 3, 2, 2, 0, 1, 4, 5,
       3, 3, 2, 2, 0, 1, 4, 5, 3, 3, 2, 2, 0, 1, 4, 5, 3, 3, 2, 2, 0, 1,
       4, 5, 3, 3, 2, 2, 0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [15]:
import sklearn
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
iris =load_iris()

In [17]:
iris_data=iris['data']
iris_label= iris['target']

In [24]:
iris_df = pd.DataFrame(data = iris_data, columns = iris['feature_names'])
iris_df 


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [19]:
import pandas as pd

In [22]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [23]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [25]:
iris_df['label'] = iris['target'] 


In [26]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [28]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [32]:
labels=encoder.fit_transform(iris['target_names'])
labels

array([0, 1, 2], dtype=int64)

In [29]:
# 사이킷런은 문자열로 바꿔도 잘 작동됨 

In [36]:
iris_df['label']=iris_df['label'].map({0:'setosa', 1:'versicolor', 2: 'virginica'})

In [37]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

         label  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [45]:
d = {'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}
d_df = pd.DataFrame(d) 
d_df

col1  col2  col3
0     1     2     3
1    11    22    33

In [42]:
d_df.values

array([[ 1,  2,  3],
       [11, 22, 33]], dtype=int64)

In [43]:
d_df.values.tolist()

[[1, 2, 3], [11, 22, 33]]

In [46]:
d_df.values.flatten().tolist() 


[1, 2, 3, 11, 22, 33]

In [48]:
li = d_df.values.tolist()
li[0]+li[1] 


[1, 2, 3, 11, 22, 33]

In [49]:
np.sort  정렬된 상태로 보여줌
ndarray.sort() 의 차이는? 기존입력값을 변경해주고 저장


SyntaxError: invalid syntax (3041045336.py, line 1)

In [55]:
X_train, X_test, y_train, y_test=train_test_split(iris_data, iris_label, test_size=0.3) 


In [57]:
from sklearn.preprocessing import OneHotEncoder
# 데이터가 커져서 잘안씀

In [58]:
items=["TV","전자레인지","컴퓨터","선풍기","선풍기","믹서","믹서"]

In [63]:
encoder=OneHotEncoder()


In [64]:
np.array(items)

array(['TV', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'], dtype='<U5')

In [69]:
items=np.array(items).reshape(-1,1)
items

array([['TV'],
       ['전자레인지'],
       ['컴퓨터'],
       ['선풍기'],
       ['선풍기'],
       ['믹서'],
       ['믹서']], dtype='<U5')

In [70]:
encoder.fit(items) # 5개로 틀을잡아주는 fit 중복이지만 5개

OneHotEncoder()

In [71]:
one_hot_labels= encoder.transform(items)
one_hot_labels

<7x5 sparse matrix of type '<class 'numpy.float64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [72]:
one_hot_labels.toarray()

array([[1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [74]:
items=["TV","전자레인지","컴퓨터","선풍기","선풍기","믹서","믹서"]
pd.get_dummies(items) # 원핫인코딩

TV  믹서  선풍기  전자레인지  컴퓨터
0   1   0    0      0    0
1   0   0    0      1    0
2   0   0    0      0    1
3   0   0    1      0    0
4   0   0    1      0    0
5   0   1    0      0    0
6   0   1    0      0    0

In [75]:
cross Validation 교차검증

SyntaxError: invalid syntax (103700064.py, line 1)

In [81]:
iris = load_iris()                   # 파일부르기

iris_data = iris.data
                # data(정보)와 target(매치대상) 저장
iris_label= iris.target


X_train,X_test,Y_train,Y_test = train_test_split(iris_data,iris_label, test_size=0.3)
                                     # 학습과 테스트 구분

dt_clf=DecisionTreeClassifier()      # 의사결정 트리 
    
dt_clf.fit(X_train,Y_train)
Y_pred = dt_clf.predict(X_test)      # 학습실행, 예측
from sklearn.metrics import accuracy_score # 정확도 점수 봄
accuracy_score(Y_test,Y_pred) 


0.9111111111111111

In [82]:
검증은 test x랑 y 한번씩 대응하고 학습함

교차검증은 1234를 테스트셋 잡고 5를 검증하고 1245하고 3검증 1345하고 2검증 5번검증

SyntaxError: invalid syntax (2629400120.py, line 1)

In [200]:
k-fold : 5-fold

SyntaxError: illegal target for annotation (706836719.py, line 1)

In [113]:
cv_accuracy=[]
n_iter=0

for train_index,test_index in kfold.split(iris_data):
    X_train, X_test=iris_data[train_index],iris_data[test_index] # 인덱스의 값 봄
    y_train, y_test=iris_label[train_index],iris_label[test_index]
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    accuracy=accuracy_score(y_test,pred)
    
    accuracy_score(y_test, pred) 
    cv_accuracy.append(accuracy)
    print("개별 검증 정확도:", cv_accuracy)
print("평균 검증 정확도:", np.mean(cv_accuracy))    



개별 검증 정확도: [1.0]
개별 검증 정확도: [1.0, 0.9666666666666667]
개별 검증 정확도: [1.0, 0.9666666666666667, 0.9]
개별 검증 정확도: [1.0, 0.9666666666666667, 0.9, 0.9333333333333333]
개별 검증 정확도: [1.0, 0.9666666666666667, 0.9, 0.9333333333333333, 0.8333333333333334]
평균 검증 정확도: 0.9266666666666665


In [115]:
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [201]:
y_train

array([1, 2, 0, 0, 1, 2, 0, 0, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 2, 2, 1, 0, 0, 1, 0, 2, 2, 0, 0, 2, 2, 1, 2, 2, 1, 1,
       2, 1, 2, 1, 0, 2, 0, 1, 1, 2, 1, 0, 1, 2, 2, 2, 0, 2, 0, 2, 2, 0,
       0, 2, 0, 1, 2, 2, 0, 2, 0, 1, 0, 2, 0, 2, 1, 0, 2, 0, 0, 2, 0, 1,
       2, 1, 2, 0, 1, 1, 2, 0, 2, 1, 2, 1, 2, 1, 0, 2, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1])

In [112]:
from sklearn.model_selection import KFold
kfold=KFold(n_splits=5)
for train_index,test_index in kfold.split(iris_data): # 인덱스 반환 
     print(train_index,test_index) # 트레인 인덱스와 테스트 인덱스를 쪼갠게 5개 있음 
        # 120개 30개로 쪼갬 iris_data의 인덱스를 120 30으로
        # 인덱스를 하는 이유는 트레이닝에서 2열심히 해도 test에 2가없으면 무용지물
        # 150개중 012가 0은 100개 1은 40개 2는 10개 편중된 데이터라면
        # train과 test에 골고루 분류된어야함 
        #stratified 계층, 층화 전체에서 비율에 맞게 뽐음 

[ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 1

In [101]:
from sklearn.model_selection import KFold


In [114]:
iris = load_iris()                   # 파일부르기

iris_data = iris.data
                # data(정보)와 target(매치대상) 저장
iris_label= iris.target


dt_clf = DecisionTreeClassifier()      # 의사결정 트리 
kfold = KFold(n_splits=5)

cv_accuracy = []

# KFold객체의 split( ) 호출하면 폴드 별 학습용, 검증용 테스트의 인덱스를 반환한다. 이거 중요함.  
for train_index, test_index  in kfold.split(iris_data): 
    
    # print(train_index, test_index)
    # print("---"*10)
    # kfold.split( )으로 반환된 인덱스를 이용하여 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = iris_data[train_index], iris_data[test_index]
    y_train, y_test = iris_label[train_index], iris_label[test_index]

    
    dt_clf.fit(X_train , y_train)    
    pred = dt_clf.predict(X_test)
    
   
    accuracy = accuracy_score(y_test,pred)   
    cv_accuracy.append(accuracy)
 
    print("개별 검증 정확도: ", cv_accuracy)
    
print('평균 검증 정확도:', np.mean(cv_accuracy)) 

개별 검증 정확도:  [1.0]
개별 검증 정확도:  [1.0, 0.9666666666666667]
개별 검증 정확도:  [1.0, 0.9666666666666667, 0.8666666666666667]
개별 검증 정확도:  [1.0, 0.9666666666666667, 0.8666666666666667, 0.9333333333333333]
개별 검증 정확도:  [1.0, 0.9666666666666667, 0.8666666666666667, 0.9333333333333333, 0.7333333333333333]
평균 검증 정확도: 0.9


In [125]:
X=train_data =iris.data # 데이터 전체를 써버리면 안됨 
y=train_label = iris.target



In [128]:
dt_clf.fit(train_data , train_label)    
pred = dt_clf.predict(train_data) # 이미 학습하고 답아는데 예측은 이미 답을 다앎 
print('예측 정확도:', accuracy_score(trian_label, pred)) 

NameError: name 'trian_label' is not defined

In [122]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedKFold

In [203]:
iris = load_iris()                   # 파일부르기

features=iris_data = iris.data
                # data(정보)와 target(매치대상) 저장
labels=iris_label= iris.target


In [124]:
df_clf =DecisionTreeClassifier()

In [131]:
s_kfold =StratifiedKFold(n_splits=3)
cv_accuracy=[]

In [204]:
for train_index, test_index in s_kfold.split(features):
    print(train_index)
    print(test_index)
    print()

TypeError: split() missing 1 required positional argument: 'y'

In [137]:
for train_index, test_index in s_kfold.split(features,labels):
    #print(train_index)
    #print(test_index)
    #print()
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = labels[train_index], labels[test_index]
    
    dt_clf.fit(X_train, y_train)# x와 y의 관계
    pred=dt_clf.predict(X_test)
    
    acc= accuracy_score(y_test, pred)
    cv_accuracy.append(acc)
    print("개별정확도:", acc)

print("정확도모음:", cv_accuracy)

개별정확도: 0.98
개별정확도: 0.92
개별정확도: 1.0
정확도모음: [0.98, 0.92, 1.0, 0.98, 0.92, 1.0]


In [139]:
np.mean(cv_accuracy).round(4)

0.9667

In [140]:
## cross _val_score()

In [141]:
from sklearn.model_selection import cross_val_score, cross_validate

In [143]:
data=X=train_data =iris.data # 데이터 전체를 써버리면 안됨 
label=y=train_label = iris.target


In [145]:
scores=cross_val_score(dt_clf, data,label, scoring='accuracy',cv=3)
scores
#위에서 한거 쉽게함 

array([0.98, 0.92, 1.  ])

In [148]:
np.mean(scores).round(4)

0.9667

In [149]:
GridSearch

NameError: name 'GridSearch' is not defined

In [150]:
grid_parameters={'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [151]:
from sklearn.model_selection import GridSearchCV

In [155]:
X_train,X_test,y_train,y_test = train_test_split(iris_data,iris_label,
                                                 test_size=0.2,
                                                random_state=121)
grid_parameters={'max_depth':[1,2,3], 'min_samples_split':[2,3]}
grid_tree=GridSearchCV(dt_clf, param_grid=grid_parameters,cv=3, refit=True)

In [156]:
grid_tree.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [157]:
grid_tree.cv_results_

{'mean_fit_time': array([0.00033251, 0.00033251, 0.00066519, 0.        , 0.0003322 ,
        0.00066487]),
 'std_fit_time': array([0.00047025, 0.00047025, 0.00047036, 0.        , 0.0004698 ,
        0.00047013]),
 'mean_score_time': array([0.00033236, 0.        , 0.        , 0.0003322 , 0.00033251,
        0.        ]),
 'std_score_time': array([0.00047002, 0.        , 0.        , 0.0004698 , 0.00047025,
        0.        ]),
 'param_max_depth': masked_array(data=[1, 1, 2, 2, 3, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_min_samples_split': masked_array(data=[2, 3, 2, 3, 2, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'max_depth': 1, 'min_samples_split': 2},
  {'max_depth': 1, 'min_samples_split': 3},
  {'max_depth': 2, 'min_samples_split': 2},
  {'max_depth': 2, 'min_samples_split': 3},
  {'max_depth': 3, 'min_sample

In [158]:
grid_tree.best_params_# 여러개중 가장 성능좋은 것

{'max_depth': 3, 'min_samples_split': 2}

In [159]:
    1  2  3
  2 12 22 23
  3 31 32 33 # 이 파라미트 격자형을 스스로 다돌려봄 grid 격자판을 돌려봄 
    # 그중 제일 성능좋은 것 

SyntaxError: invalid syntax (4062527555.py, line 1)

In [161]:
pd.DataFrame(grid_tree.cv_results_).iloc[:,5:]

param_min_samples_split                                    params  \
0                       2  {'max_depth': 1, 'min_samples_split': 2}   
1                       3  {'max_depth': 1, 'min_samples_split': 3}   
2                       2  {'max_depth': 2, 'min_samples_split': 2}   
3                       3  {'max_depth': 2, 'min_samples_split': 3}   
4                       2  {'max_depth': 3, 'min_samples_split': 2}   
5                       3  {'max_depth': 3, 'min_samples_split': 3}   

   split0_test_score  split1_test_score  split2_test_score  mean_test_score  \
0              0.700                0.7               0.70         0.700000   
1              0.700                0.7               0.70         0.700000   
2              0.925                1.0               0.95         0.958333   
3              0.925                1.0               0.95         0.958333   
4              0.975                1.0               0.95         0.975000   
5              0.975                1.0               0.95         0.975000   

   std_test_score  rank_test_score  
0    1.110223e-16                5  
1    1.110223e-16                5  
2    3.118048e-02                3  
3    3.118048e-02                3  
4    2.041241e-02                1  
5    2.041241e-02                1

In [162]:
grid_tree.best_score_

0.975

In [163]:
pred=grid_tree.predict(X_test)

In [164]:
pred # pred는 결과 값이다. 

array([1, 2, 1, 0, 0, 1, 1, 1, 1, 2, 2, 1, 1, 0, 0, 2, 1, 0, 2, 0, 2, 2,
       1, 1, 1, 1, 0, 0, 2, 2])

In [165]:
accuracy_score(y_test, pred)

0.9666666666666667

In [166]:
계층 30 50 70 이면  3 5 7비율로 뽑음 
집락추출 -row를 뽑음 


SyntaxError: invalid syntax (811750598.py, line 1)

In [ ]:
# 피처 스케일링과 정규화

In [167]:
Feature Scaling 단위가 다른 것을 단위가 같은 것 처럼 
정규화 최솟값 0과  최댓값을 1로 만듬
표준화 

SyntaxError: invalid syntax (3012661225.py, line 1)

In [168]:
# 정규화(Nomalization)

In [172]:
iris_df=iris['data']
iris_df=pd.DataFrame(iris_df)
iris_df

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [173]:
iris_df.max()

0    7.9
1    4.4
2    6.9
3    2.5
dtype: float64

In [174]:
iris_df.min()

0    4.3
1    2.0
2    1.0
3    0.1
dtype: float64

In [175]:
2,3,4,5
0     1
_________
 2 3 4 5
    2에서 5까지 거리 3을 1로바꾸기는 같은수로 나눔 5-2/5-2 =1 
    0이 나오는 이유 2-2/5-2 = 0 
    3-2/5-2= 1/3

SyntaxError: invalid syntax (1826683938.py, line 2)

In [177]:
def min_max(x):
    return   ( x -x.min() )/(x.max()-x.min())

In [178]:
iris_df.apply(min_max)

0         1         2         3
0    0.222222  0.625000  0.067797  0.041667
1    0.166667  0.416667  0.067797  0.041667
2    0.111111  0.500000  0.050847  0.041667
3    0.083333  0.458333  0.084746  0.041667
4    0.194444  0.666667  0.067797  0.041667
..        ...       ...       ...       ...
145  0.666667  0.416667  0.711864  0.916667
146  0.555556  0.208333  0.677966  0.750000
147  0.611111  0.416667  0.711864  0.791667
148  0.527778  0.583333  0.745763  0.916667
149  0.444444  0.416667  0.694915  0.708333

[150 rows x 4 columns]

In [179]:
iris_df.apply(min_max).max()

0    1.0
1    1.0
2    1.0
3    1.0
dtype: float64

In [182]:
iris_df.apply(lambda x: ( x -x.min() )/(x.max()-x.min()))

0         1         2         3
0    0.222222  0.625000  0.067797  0.041667
1    0.166667  0.416667  0.067797  0.041667
2    0.111111  0.500000  0.050847  0.041667
3    0.083333  0.458333  0.084746  0.041667
4    0.194444  0.666667  0.067797  0.041667
..        ...       ...       ...       ...
145  0.666667  0.416667  0.711864  0.916667
146  0.555556  0.208333  0.677966  0.750000
147  0.611111  0.416667  0.711864  0.791667
148  0.527778  0.583333  0.745763  0.916667
149  0.444444  0.416667  0.694915  0.708333

[150 rows x 4 columns]

In [183]:
from sklearn.preprocessing import MinMaxScaler

In [184]:
# MinmaxScaler 사용하기 

In [185]:
scaler=MinMaxScaler()

In [186]:
scaler.fit(iris_df) # 최댓값과 최솟값을 잡아주는 과정
iris_scaled=scaler.transform(iris_df)
iris_scaled

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [187]:
scaler.fit_transform(iris_df)

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [188]:
X_train, X_test= train_test_split(iris_data)

In [ ]:
scaler.fit(X_train) # 여기서 기준 잡음 최댓값 최솟값
scaler.transform() 


1,2,1,2 

In [190]:
X_test

scaler.fit() # 여기서 기준 새로 잡으면 수가 다름 
scaler.transform()
통채로 정규화 하고 쪼개라

SyntaxError: invalid syntax (990983574.py, line 5)

In [191]:
 # 표준화 (Standardize)

In [192]:
x-mu/sigma 평균을 0 표준편차 1 모든 것을 

SyntaxError: invalid syntax (1608373432.py, line 1)

In [194]:
def standardize(x):
    return (x-x.mean())/x.std()

In [195]:
iris_df.apply(standardize)

0         1         2         3
0   -0.897674  1.015602 -1.335752 -1.311052
1   -1.139200 -0.131539 -1.335752 -1.311052
2   -1.380727  0.327318 -1.392399 -1.311052
3   -1.501490  0.097889 -1.279104 -1.311052
4   -1.018437  1.245030 -1.335752 -1.311052
..        ...       ...       ...       ...
145  1.034539 -0.131539  0.816859  1.443994
146  0.551486 -1.278680  0.703564  0.919223
147  0.793012 -0.131539  0.816859  1.050416
148  0.430722  0.786174  0.930154  1.443994
149  0.068433 -0.131539  0.760211  0.788031

[150 rows x 4 columns]

In [196]:
iris_df.apply(standardize).mean() #e-15 16 은 0에 가까움

0   -1.457168e-15
1   -1.638319e-15
2   -1.292300e-15
3   -5.543714e-16
dtype: float64

In [197]:
from sklearn.preprocessing import StandardScaler

In [199]:
scaler= StandardScaler()
scaler.fit(iris_df)
iris_scaled=scaler.transform(iris_df)
iris_scaled

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [ ]:
              실제 정답 
                     포지티브      네거티브
실험 결과 포지티브   트루 포지티브, 펄스 네거티브(네거티브라했는데 틀림 )
         네거티브       펄스 네거티브  트르 네커티브(네거티브라 했는데 맞음) 
네거티브 포지티브는 예측치임