# 정리

In [ ]:
p = re.compile('(?<=://)\w+') # 스에이스가 아닌것 찾음. 은 포함 안됨 
p.findall(s)         

p = re.compile(".+(?=://)") #뒤에서 부터 찾는데 스페이스도 인식
p.findall(s)                  # 그래서 :// 인식 잘항ㄴ함    

p = re.compile(r"(?P<repeat>\w+)\s+(?P=repeat)") # 그룹 이름 지어주기

for i in p.finditer(data):
    print(i) 
    
data= req.urlopen("http://daum.net").read().decode('utf-8')

p= re.compile("htt[:./\w]*[.]{1}js")# .or / or w 가 있음
li = p.findall(data)
for i in li:
    print(li)
p = re.compile("[가-힣]+")
r = p.findall(data)

for i in r:
    print(i) 
    
text = '''<p>이른 아침 문을 여는 빵집입니다</p>
<h1>아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요</h1>
<h5>이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다</h5>
<p>가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다</p>
<p>참고로 식빵 나오는 시간은 오전시시 입니다</pp>
''' 
p = re.compile("[가-힣][\w\s\d]*") 
p.findall(text)    

a= np.array([1,2,3], dtype ='float')
a.dtype
# 64 float은 8바이트

np.array([[1,2,3,4],[5,6,7,8]]) #2차원 중첩리스트
np.arange(12).reshape(3, -1) # -1은 자동으로 계산

np.arange(24).reshape(2,3,4) # 3행 4열이 두개 나옴 2가 z축이니까 3이 y/ 4는x
# 종이가 2장 겹침 

f = np.array([[1,2,3,4],[4,5,6,7]])
g =np.array([5]) #5가 가로세로 맞춰줘서 늘림
f+g             

In [ ]:
지문등록하기

In [ ]:
match: 처음부터 맞는 거
search:  처음부터 중간부터 맞는거
findall: 전부다 
finditer: iterable한거 찾음 

In [1]:
match: 문자열 처음부터 검색
search: 문자열 전체를 검색
findall: 리스트로 돌려줌
finditer: 반복 가능한 객체를 돌려줌 iterable 차증ㅁ

SyntaxError: invalid syntax (1815138655.py, line 1)

In [2]:
match 객체의 메서드 
group() start end span

SyntaxError: invalid syntax (2557914459.py, line 1)

In [3]:
import re
a = "Life is too short".lower()
re.findall("[a-z]+", a) 

['life', 'is', 'too', 'short']

In [4]:
p= re.compile("[A-z]+")
print(p.findall(a))

['life', 'is', 'too', 'short']


In [5]:
\W = [^a-zA-Z0-9_]

SyntaxError: unexpected character after line continuation character (2880797391.py, line 1)

In [6]:
data = """이름 : 김철수 전화번호 :010-1234-1234 나이: 30 성별:남""" 

In [8]:
p= re.compile("\d+")
print(p.search(data).group())

010


In [9]:
p = re.compile("\d+")
print(re.findall(p, data))

['010', '1234', '1234', '30']


In [10]:
p = re.compile(r'\d+[-]\d+[-]\d+')
print(p.findall(data)) 

['010-1234-1234']


In [11]:
s =:"blach blue and brown
p= re.compile("")

SyntaxError: unterminated string literal (detected at line 1) (1498631430.py, line 1)

In [2]:
import re
s = 'black, blue and brown'
print(re.findall("bl\w*", s))

['black', 'blue']


In [3]:
s = "black, blue and brown"
p = re.compile("black|blue")
print(re.findall(p, s)) 

NameError: name 're' is not defined

In [22]:
s= "http://naver.com http://google.com ftp://daum.net" 
p =re.compile("\w+(?=://)")
p.findall(s)


['http', 'http', 'ftp']

In [6]:
import re

In [20]:
p = re.compile("\w+(?=://)")
p.findall(s) 

['http', 'http', 'ftp']

In [21]:
p = re.compile(".+(?=://)") #뒤에서 부터 찾는데 스페이스도 인식
p.findall(s)                  # 그래서 :// 인식 잘항ㄴ함       

['http://naver.com http://google.com ftp']

In [14]:
p = re.compile("\w+(?=:)")
re.findall(p, s) 

['http', 'http', 'ftp']

In [25]:
p = re.compile('(?<=/)\S+')
p.findall(s) 

['/naver.com', '/google.com', '/daum.net']

In [1]:
p = re.compile('(?<=://)\w+') # 스에이스가 아닌것 찾음. 은 포함 안됨 
p.findall(s)                        

NameError: name 're' is not defined

In [47]:
data = '''안녕하세요 그리고 그리고 안녕하세요 또또 안녕하세요 그런데 그런데 인녕하세요 끝 끝'''

In [29]:
p= re.compile("/")
p.findall(data)

[]

In [48]:
p = re.compile(r"(?P<repeat>\w+)\s+(?P=repeat)") # 그룹 이름 지어주기

for i in p.finditer(data):
    print(i) 

<re.Match object; span=(6, 13), match='그리고 그리고'>
<re.Match object; span=(29, 36), match='그런데 그런데'>
<re.Match object; span=(43, 46), match='끝 끝'>


In [38]:
data = re.findall("\w+\S", data)
set(sorted(data)) 

{'그런데', '그리고', '또또', '안녕하세요', '인녕하세요'}

In [43]:
data = re.findall("\w+", data)
set(sorted(data)) 

{'그런데', '그리고', '끝', '또또', '안녕하세요', '인녕하세요'}

In [45]:
data = re.findall("\w*\S", data)
set(data) 

{'그런데', '그리고', '끝', '또또', '안녕하세요', '인녕하세요'}

In [5]:
import urllib.request as req
import re

In [53]:
req.urlopen("http://daum.net") # 들어가는지 응답 봄, 접근함 

In [55]:
req.urlopen("http://daum.net").read(). # 코드 가져옴 읽을수 없음

SyntaxError: invalid syntax (1765858542.py, line 1)

In [6]:
data= req.urlopen("http://daum.net").read().decode('utf-8')

In [58]:
data.

SyntaxError: invalid syntax (1519389772.py, line 1)

In [79]:
p= re.compile("http[:./\w]*[.]{1}js")
li = p.findall(data)
for i in li:
    print(li)

['https://t1.daumcdn.net/kas/static/na.min.js', 'http://tktapi.melon.com/kmt/landing.js', 'http://tktapi.melon.com/kmt/landing.js', 'http://tktapi.melon.com/kmt/landing.js', 'http://tktapi.melon.com/kmt/landing.js', 'https://t1.daumcdn.net/tiara/js/v1/tiara.min.js', 'https://t1.daumcdn.net/kas/static/ba.min.js']
['https://t1.daumcdn.net/kas/static/na.min.js', 'http://tktapi.melon.com/kmt/landing.js', 'http://tktapi.melon.com/kmt/landing.js', 'http://tktapi.melon.com/kmt/landing.js', 'http://tktapi.melon.com/kmt/landing.js', 'https://t1.daumcdn.net/tiara/js/v1/tiara.min.js', 'https://t1.daumcdn.net/kas/static/ba.min.js']
['https://t1.daumcdn.net/kas/static/na.min.js', 'http://tktapi.melon.com/kmt/landing.js', 'http://tktapi.melon.com/kmt/landing.js', 'http://tktapi.melon.com/kmt/landing.js', 'http://tktapi.melon.com/kmt/landing.js', 'https://t1.daumcdn.net/tiara/js/v1/tiara.min.js', 'https://t1.daumcdn.net/kas/static/ba.min.js']
['https://t1.daumcdn.net/kas/static/na.min.js', 'http://tk

In [7]:
p = re.compile("http[:./\w]*[.]js")
p.findall(data)

['https://t1.daumcdn.net/kas/static/na.min.js',
 'http://tktapi.melon.com/kmt/landing.js',
 'http://tktapi.melon.com/kmt/landing.js',
 'http://tktapi.melon.com/kmt/landing.js',
 'http://tktapi.melon.com/kmt/landing.js',
 'https://t1.daumcdn.net/tiara/js/v1/tiara.min.js',
 'https://t1.daumcdn.net/kas/static/ba.min.js']

In [83]:
p= re.compile("htt[:./\w]*[.]{1}js")# .or / or w 가 있음
li = p.findall(data)
for i in li:
    print(li)

['https://t1.daumcdn.net/kas/static/na.min.js', 'http://tktapi.melon.com/kmt/landing.js', 'http://tktapi.melon.com/kmt/landing.js', 'http://tktapi.melon.com/kmt/landing.js', 'http://tktapi.melon.com/kmt/landing.js', 'https://t1.daumcdn.net/tiara/js/v1/tiara.min.js', 'https://t1.daumcdn.net/kas/static/ba.min.js']
['https://t1.daumcdn.net/kas/static/na.min.js', 'http://tktapi.melon.com/kmt/landing.js', 'http://tktapi.melon.com/kmt/landing.js', 'http://tktapi.melon.com/kmt/landing.js', 'http://tktapi.melon.com/kmt/landing.js', 'https://t1.daumcdn.net/tiara/js/v1/tiara.min.js', 'https://t1.daumcdn.net/kas/static/ba.min.js']
['https://t1.daumcdn.net/kas/static/na.min.js', 'http://tktapi.melon.com/kmt/landing.js', 'http://tktapi.melon.com/kmt/landing.js', 'http://tktapi.melon.com/kmt/landing.js', 'http://tktapi.melon.com/kmt/landing.js', 'https://t1.daumcdn.net/tiara/js/v1/tiara.min.js', 'https://t1.daumcdn.net/kas/static/ba.min.js']
['https://t1.daumcdn.net/kas/static/na.min.js', 'http://tk

In [76]:
p = re.compile("https://\S+[.]js")
li = re.findall(p, data)
for i in li:
    print(i) 

https://t1.daumcdn.net/kas/static/na.min.js
https://t1.daumcdn.net/tiara/js/v1/tiara.min.js
https://t1.daumcdn.net/top/tiller-pc/lib/1636937121956/polyfill.min.js
https://t1.daumcdn.net/top/tiller-pc/h/production/20220915_111213/index.js
https://t1.daumcdn.net/kas/static/ba.min.js
https://t1.daumcdn.net/top/tiller-pc/1655174491872/tiller-pc-suggest.js


In [78]:
p = re.compile("http://.*[.]js$") # 달러는 한문장으로 잡아서 js로 잡음
li = p.findall(data)
for i in li:
    print(i) 


In [80]:
p = re.compile("https://\S+[.]js")
li = re.findall(p, data)
for i in li:
    print(i) 

https://t1.daumcdn.net/kas/static/na.min.js
https://t1.daumcdn.net/tiara/js/v1/tiara.min.js
https://t1.daumcdn.net/top/tiller-pc/lib/1636937121956/polyfill.min.js
https://t1.daumcdn.net/top/tiller-pc/h/production/20220915_111213/index.js
https://t1.daumcdn.net/kas/static/ba.min.js
https://t1.daumcdn.net/top/tiller-pc/1655174491872/tiller-pc-suggest.js


In [8]:
data = """<div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="true" class="M_704" style="display: block;"><span class="WoYOw">이른 아침 문을 여는 빵집입니다. 아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요. 이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다.  가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다.  참고로, 식빵 나오는 시간은 오전11시~12시 입니다. 빵 가격은 가성비 괜찮은 편이고 맛은 무난합니다. </span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">우연히 들어갔는데 사장님이 따뜻하고 친절하셔서 제주도 이미지마저 좋게 느껴졌어요. 그리고 무엇보다 빵이 정말 맛있어요. 제주도에서 원탑입니다!!! 여기보다 두배는 ...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">맛집검색하다가 스쳐지나갔는데 숙소근처에 있길래 들렸어요!!  시식하는빵도 있고  빵구매하는데 서비스로 흰색찹살떡??도 주시고 친절하세요! 인절미빵 강추입니다!  ...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">인절미빵. 먹물치즈빵? 제일 맛있었고 대파빵은 삼겹살을 부르는 꽤 매운 맛이었어요! 빵이 대체로 다~~~~맛있고 친절하십니다 주차는 근처 공영주차장에 하면 됩니다 다...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">사진을 제대로 못찍엇는데 뒤에 비닐로 싸진 빵들이에요 ㅋㅋㅋ  여기 진짜 촤고에요 보니 동네찐로컬맛집같아요 빵종류도 많고 각 빵마다 시식빵이 있는데 크기가 넘 커서...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">성산 여행하는 동안 두번이나 방문했어요 빵도 특색있고 하나하나 다 맛있고 사장님도 직원분도 친절하시고  커피도 무료로 먹을수 있게 해주시고 살때마다 서비스빵을 주...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">사장님 너무 친절하시고 빵이 진짜 맛있어요.. 미친 맛,,,,🥹가격이 타 빵집보다 훠얼씬 저렴한데  맛이 훠얼씬 맛있네요,,,??!?! 저희 동네에 있었음 매일 가고싶네요ㅠㅠㅠ …</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">재료를 아끼지 않으세요 눚은시간 방문했는데도 손님들이 꽤 왔어요 마늘바게트에는 소스를 아끼지 않았고 다른빵들도 크림이 듬뿍 들어 있었어요 서비스도 주시고 시식…</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div>""" 

In [100]:
p = re.compile("[가-힣]+")
r = p.findall(data)

for i in r:
    print(i) 

이른
아침
문을
여는
빵집입니다
아침식사로
빵을
사러
가기엔
좋지만
매장안에서
드실
공간은
없어요
이
빵집은
특이하게도
물
또는
커피를
무료로
텀블러에
담아갈수
있습니다
가볍게
아침을
해결하고자
하는
여행자나
현지인은
들러보면
좋을
장소입니다
참고로
식빵
나오는
시간은
오전
시
시
입니다
빵
가격은
가성비
괜찮은
편이고
맛은
무난합니다
우연히
들어갔는데
사장님이
따뜻하고
친절하셔서
제주도
이미지마저
좋게
느껴졌어요
그리고
무엇보다
빵이
정말
맛있어요
제주도에서
원탑입니다
여기보다
두배는
내용
더보기
맛집검색하다가
스쳐지나갔는데
숙소근처에
있길래
들렸어요
시식하는빵도
있고
빵구매하는데
서비스로
흰색찹살떡
도
주시고
친절하세요
인절미빵
강추입니다
내용
더보기
인절미빵
먹물치즈빵
제일
맛있었고
대파빵은
삼겹살을
부르는
꽤
매운
맛이었어요
빵이
대체로
다
맛있고
친절하십니다
주차는
근처
공영주차장에
하면
됩니다
다
내용
더보기
사진을
제대로
못찍엇는데
뒤에
비닐로
싸진
빵들이에요
여기
진짜
촤고에요
보니
동네찐로컬맛집같아요
빵종류도
많고
각
빵마다
시식빵이
있는데
크기가
넘
커서
내용
더보기
성산
여행하는
동안
두번이나
방문했어요
빵도
특색있고
하나하나
다
맛있고
사장님도
직원분도
친절하시고
커피도
무료로
먹을수
있게
해주시고
살때마다
서비스빵을
주
내용
더보기
사장님
너무
친절하시고
빵이
진짜
맛있어요
미친
맛
가격이
타
빵집보다
훠얼씬
저렴한데
맛이
훠얼씬
맛있네요
저희
동네에
있었음
매일
가고싶네요
내용
더보기
재료를
아끼지
않으세요
눚은시간
방문했는데도
손님들이
꽤
왔어요
마늘바게트에는
소스를
아끼지
않았고
다른빵들도
크림이
듬뿍
들어
있었어요
서비스도
주시고
시식
내용
더보기


In [115]:
p = re.compile("[가-힣].+[가-힣]")# 한글과 한글 사이에 뭐가 있어도 좋아
li = p.findall(data)
li 

['이른 아침 문을 여는 빵집입니다. 아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요. 이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다.  가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다.  참고로, 식빵 나오는 시간은 오전11시~12시 입니다. 빵 가격은 가성비 괜찮은 편이고 맛은 무난합니다. </span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">우연히 들어갔는데 사장님이 따뜻하고 친절하셔서 제주도 이미지마저 좋게 느껴졌어요. 그리고 무엇보다 빵이 정말 맛있어요. 제주도에서 원탑입니다!!! 여기보다 두배는',
 '내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">맛집검색하다가 스쳐지나갔는데 숙소근처에 있길래 들렸어요!!  시식하는빵도 있고  빵구매하는데 서비스로 흰색찹살떡??도 주시고 친절하세요! 인절미빵 강추입니다',
 '내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">인절미빵. 먹물치즈빵? 제일 맛있었고 대파빵은 삼겹살을 부르는 꽤 매운 맛이었어요! 빵이 대체로 다~~~~맛있고 친절하십니다 주차는 근처 공영주차장에 하면 됩니다 다',
 '내용 더보기</span></s

In [108]:
p = re.compile("[가-힣][\d\w\s]*")
li = p.findall(data)
li 

['이른 아침 문을 여는 빵집입니다',
 '아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요',
 '이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다',
 '가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다',
 '참고로',
 '식빵 나오는 시간은 오전11시',
 '시 입니다',
 '빵 가격은 가성비 괜찮은 편이고 맛은 무난합니다',
 '우연히 들어갔는데 사장님이 따뜻하고 친절하셔서 제주도 이미지마저 좋게 느껴졌어요',
 '그리고 무엇보다 빵이 정말 맛있어요',
 '제주도에서 원탑입니다',
 '여기보다 두배는 ',
 '내용 더보기',
 '맛집검색하다가 스쳐지나갔는데 숙소근처에 있길래 들렸어요',
 '시식하는빵도 있고  빵구매하는데 서비스로 흰색찹살떡',
 '도 주시고 친절하세요',
 '인절미빵 강추입니다',
 '내용 더보기',
 '인절미빵',
 '먹물치즈빵',
 '제일 맛있었고 대파빵은 삼겹살을 부르는 꽤 매운 맛이었어요',
 '빵이 대체로 다',
 '맛있고 친절하십니다 주차는 근처 공영주차장에 하면 됩니다 다',
 '내용 더보기',
 '사진을 제대로 못찍엇는데 뒤에 비닐로 싸진 빵들이에요 ㅋㅋㅋ  여기 진짜 촤고에요 보니 동네찐로컬맛집같아요 빵종류도 많고 각 빵마다 시식빵이 있는데 크기가 넘 커서',
 '내용 더보기',
 '성산 여행하는 동안 두번이나 방문했어요 빵도 특색있고 하나하나 다 맛있고 사장님도 직원분도 친절하시고  커피도 무료로 먹을수 있게 해주시고 살때마다 서비스빵을 주',
 '내용 더보기',
 '사장님 너무 친절하시고 빵이 진짜 맛있어요',
 '미친 맛',
 '가격이 타 빵집보다 훠얼씬 저렴한데  맛이 훠얼씬 맛있네요',
 '저희 동네에 있었음 매일 가고싶네요ㅠㅠㅠ ',
 '내용 더보기',
 '재료를 아끼지 않으세요 눚은시간 방문했는데도 손님들이 꽤 왔어요 마늘바게트에는 소스를 아끼지 않았고 다른빵들도 크림이 듬뿍 들어 있었어요 서비스도 주시고 시식',
 '내용 더보기']

In [110]:
p = re.compile("[가-힣][\d\w\s]*")
li = p.findall(data)
li 

['이른 아침 문을 여는 빵집입니다',
 '아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요',
 '이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다',
 '가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다',
 '참고로',
 '식빵 나오는 시간은 오전11시',
 '시 입니다',
 '빵 가격은 가성비 괜찮은 편이고 맛은 무난합니다',
 '우연히 들어갔는데 사장님이 따뜻하고 친절하셔서 제주도 이미지마저 좋게 느껴졌어요',
 '그리고 무엇보다 빵이 정말 맛있어요',
 '제주도에서 원탑입니다',
 '여기보다 두배는 ',
 '내용 더보기',
 '맛집검색하다가 스쳐지나갔는데 숙소근처에 있길래 들렸어요',
 '시식하는빵도 있고  빵구매하는데 서비스로 흰색찹살떡',
 '도 주시고 친절하세요',
 '인절미빵 강추입니다',
 '내용 더보기',
 '인절미빵',
 '먹물치즈빵',
 '제일 맛있었고 대파빵은 삼겹살을 부르는 꽤 매운 맛이었어요',
 '빵이 대체로 다',
 '맛있고 친절하십니다 주차는 근처 공영주차장에 하면 됩니다 다',
 '내용 더보기',
 '사진을 제대로 못찍엇는데 뒤에 비닐로 싸진 빵들이에요 ㅋㅋㅋ  여기 진짜 촤고에요 보니 동네찐로컬맛집같아요 빵종류도 많고 각 빵마다 시식빵이 있는데 크기가 넘 커서',
 '내용 더보기',
 '성산 여행하는 동안 두번이나 방문했어요 빵도 특색있고 하나하나 다 맛있고 사장님도 직원분도 친절하시고  커피도 무료로 먹을수 있게 해주시고 살때마다 서비스빵을 주',
 '내용 더보기',
 '사장님 너무 친절하시고 빵이 진짜 맛있어요',
 '미친 맛',
 '가격이 타 빵집보다 훠얼씬 저렴한데  맛이 훠얼씬 맛있네요',
 '저희 동네에 있었음 매일 가고싶네요ㅠㅠㅠ ',
 '내용 더보기',
 '재료를 아끼지 않으세요 눚은시간 방문했는데도 손님들이 꽤 왔어요 마늘바게트에는 소스를 아끼지 않았고 다른빵들도 크림이 듬뿍 들어 있었어요 서비스도 주시고 시식',
 '내용 더보기']

In [124]:
p = re.compile("[^가-힣0-9\s.~]") # 한글아닌것 숫자 아닌것 스페이스 아닌것 고름
new_data =p.sub("", data) # 공백을 데이터로 대체함 
new_data

'      704   이른 아침 문을 여는 빵집입니다. 아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요. 이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다.  가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다.  참고로 식빵 나오는 시간은 오전11시~12시 입니다. 빵 가격은 가성비 괜찮은 편이고 맛은 무난합니다.       704   우연히 들어갔는데 사장님이 따뜻하고 친절하셔서 제주도 이미지마저 좋게 느껴졌어요. 그리고 무엇보다 빵이 정말 맛있어요. 제주도에서 원탑입니다 여기보다 두배는 ... 309 \n.3.2000\n 0 0 12 7 3  11.47.52.74.74 0 0 01.04 04.4 4.45.011.57.52.74.74 0 1 0 .53 1.575.12 5.08.5.5 0 0 0 .7 05.125.08.74.74 0 0 0 01.05 내용 더보기      704   맛집검색하다가 스쳐지나갔는데 숙소근처에 있길래 들렸어요  시식하는빵도 있고  빵구매하는데 서비스로 흰색찹살떡도 주시고 친절하세요 인절미빵 강추입니다  ... 309 \n.3.2000\n 0 0 12 7 3  11.47.52.74.74 0 0 01.04 04.4 4.45.011.57.52.74.74 0 1 0 .53 1.575.12 5.08.5.5 0 0 0 .7 05.125.08.74.74 0 0 0 01.05 내용 더보기      704   인절미빵. 먹물치즈빵 제일 맛있었고 대파빵은 삼겹살을 부르는 꽤 매운 맛이었어요 빵이 대체로 다~~~~맛있고 친절하십니다 주차는 근처 공영주차장에 하면 됩니다 다... 309 \n.3.2000\n 0 0 12 7 3  11.47.52.74.74 0 0 01.04 04.4 4.45.011.57.52.74.74 0 1 0 .53 1.575.12 5.08.5.5 0 0 0 .7 05.125.08.74.74 0 0 0 01.05 내용 더보기      704   사진을 제대로 못찍엇는데 뒤

In [10]:
p = re.compile("[^가-힣0-9\s.~]")
p.findall(data).

SyntaxError: invalid syntax (1935119054.py, line 2)

In [122]:
p = re.compile("[가-힣\s.~!]+")
li = p.findall(data)

for i in li:
    if i != ' ':
        print(i) 

      
   이른 아침 문을 여는 빵집입니다. 아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요. 이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다.  가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다.  참고로 식빵 나오는 시간은 오전
시~
시 입니다. 빵 가격은 가성비 괜찮은 편이고 맛은 무난합니다.       
   우연히 들어갔는데 사장님이 따뜻하고 친절하셔서 제주도 이미지마저 좋게 느껴졌어요. 그리고 무엇보다 빵이 정말 맛있어요. 제주도에서 원탑입니다 여기보다 두배는 ... 
 
.
.

 
  
.
.
.
.
.
.
.
.
.
.
.
.
 .
.
.
.
.
.
 .
.
.
.
.
.
 내용 더보기      
   맛집검색하다가 스쳐지나갔는데 숙소근처에 있길래 들렸어요  시식하는빵도 있고  빵구매하는데 서비스로 흰색찹살떡도 주시고 친절하세요 인절미빵 강추입니다  ... 
 
.
.

 
  
.
.
.
.
.
.
.
.
.
.
.
.
 .
.
.
.
.
.
 .
.
.
.
.
.
 내용 더보기      
   인절미빵. 먹물치즈빵 제일 맛있었고 대파빵은 삼겹살을 부르는 꽤 매운 맛이었어요 빵이 대체로 다~~~~맛있고 친절하십니다 주차는 근처 공영주차장에 하면 됩니다 다... 
 
.
.

 
  
.
.
.
.
.
.
.
.
.
.
.
.
 .
.
.
.
.
.
 .
.
.
.
.
.
 내용 더보기      
   사진을 제대로 못찍엇는데 뒤에 비닐로 싸진 빵들이에요   여기 진짜 촤고에요 보니 동네찐로컬맛집같아요 빵종류도 많고 각 빵마다 시식빵이 있는데 크기가 넘 커서... 
 
.
.

 
  
.
.
.
.
.
.
.
.
.
.
.
.
 .
.
.
.
.
.
 .
.
.
.
.
.
 내용 더보기      
   성산 여행하는 동안 두번이나 방문했어요 빵도 특색있고 하나하나 다 맛있고 사장님도 직원분도 친절하시고  커피도 무료로 먹을수 있게 해주시고 살때마다 서비스빵을 주... 
 

- 자주쓰이는 패턴

- 전화번호

In [ ]:
p=re.compile("010[-]\d{4}[-]\d{4}")

- 이메일

In [129]:
a= "123llo@daum.net"
p=re.compile("\w+@\w+[.]\w+")
p.findall(a)
p=re.compile("[A-z0-9]+@[A-z0-9]+[.][a-z.]+")


['123llo@daum.net']

- 주민번호 

In [133]:
a= "123456-1234567"
p.findall(a)
p = re.compile("\d{6}[-][123456]\d{6}") # 주민번호 뒷자리 는 1-6 까지 외국인 번호


In [12]:
text = '''
http://www.google.com/

https://mail.google.com/

ftp://ftp.google.com/

''' 

p = re.compile("\w+(?=:)")
p.findall(text)

['http', 'https', 'ftp']

In [144]:
p = re.compile(".*:") 
p.findall(text)

['http:', 'https:', 'ftp:']

In [148]:

p = re.compile("\S+(?=//)")# :은 문자가 아니라서 \w안됨
p.findall(text)

['http:', 'https:', 'ftp:']

In [149]:
p = re.compile(".+(?=:)")
p.findall(text)

['http', 'https', 'ftp']

In [156]:
text = '''apple: $50.24
banana: $35.25
pizza: $100
''' 
p = re.compile("(?<=[$]).+")
p.findall(text)


['50.24', '35.25', '100']

In [158]:
p = re.compile("\$.+") # \ escape
p.findall(text) 


['$50.24', '$35.25', '$100']

In [160]:
text = '''<p>이른 아침 문을 여는 빵집입니다</p>
<h1>아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요</h1>
<h5>이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다</h5>
<p>가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다</p>
<p>참고로 식빵 나오는 시간은 오전시시 입니다</pp>
''' 
p = re.compile("[가-힣][\w\s\d]*") 
p.findall(text) 

['이른 아침 문을 여는 빵집입니다',
 '아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요',
 '이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다',
 '가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다',
 '참고로 식빵 나오는 시간은 오전시시 입니다']

In [164]:
p = re.compile("(?<=<p>).+(?=<)") 
p.findall(text)

['이른 아침 문을 여는 빵집입니다',
 '가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다',
 '참고로 식빵 나오는 시간은 오전시시 입니다']

In [13]:
def add_array(n):
    array1 =np.array(range(1,n+1))
    array2 =np.array(range(1,n+1))
    array3= array1+array2
    
    return array3
    

In [148]:
def add_array():
    array1 =np.array(range(1,100+1))
    array2 =np.array(range(1,100+1))
    array3= array1+array2
    
    return array3

add_array()

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

In [ ]:
numpy numerical python  array  배열 
2d 이차원 
axis 축 2행 3열 (2,3) 액시스 0 y축 2행/액시스 1 x 축 3열
3차원 액시스 0 z축 0번 y측 1번  x축2번 
배열 차원 shape 하고 튜플로 표시 
(3, )- 1차원표현 1 행 표현 
매트릭스는 2차원 3차원은 array 

In [ ]:
넘파이 빠르다. 정교한 브로드케스팅 반복문 안씀 

In [40]:
import numpy as np

# 배열 만들기 

In [ ]:
a= np.array([1,2,3,4]) #숫자가 두개이상이면 항상 묶음 

In [15]:
a.shape #1차원중에 4개


NameError: name 'a' is not defined

In [23]:
print(a.size)

NameError: name 'a' is not defined

In [ ]:
print(a.dtype) #데이터 타닙 

In [ ]:
a= np.array([1,2,3,4.0])
a.dtype

In [ ]:
a= np.array([1,2,3,4.0], dtype ='int')
a.dtype

In [ ]:
a= np.array([1,2,3], dtype ='float')
a.dtype
# 64 float은 8바이트

In [ ]:
a= np.array([1,2,3], dtype ='float32')
a.dtype # 불필요없는 비트 버림 

In [ ]:
a= np.array([1,2,3], dtype ='float16') # 16이하는 안됨


In [ ]:
a= np.array([1,2,3], dtype ='int8')

In [ ]:
uint8 0~255 음수 쓸일 없다.

In [ ]:
array 객체속성 3가지  shape, dtype, size 


In [ ]:
numpy 데이터 타입 bool, complex number, int, str, list 


In [ ]:
list1 =[1,2,3,4]
list2 =[1,2,3,4]
list3= []
for i in range(4): # 반복문은 하나하나 가져옴
    list3.append(list1[i]+ list2[i])
list3 

In [ ]:
array1 =np.array([1,2,3,4])
array2 =np.array([1,2,3,4])

In [ ]:
array3 =array1 +array2

In [44]:
def add_list(n):
    li1 = list(range(1, n+1))
    li2 = list(range(1, n+1))
    
    li3 =[]
    for i in range(n):
        li3.append(li1[i] +li2[i])
        
    return li3   

In [48]:
def add_list():
    li1 = list(range(10000))
    li2 = list(range(10000))
    
    li3 =[]
    for i in range(10000):
        li3.append(li1[i] +li2[i])
        
    return li3   

In [33]:
add_list(10)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [19]:
import timeit

In [49]:
def add_array():
    array1 =np.array(range(10000))
    array2 =np.array(range(10000))
    array3= array1+array2
    return array3

add_array()

array([    0,     2,     4, ..., 19994, 19996, 19998])

In [50]:
print(timeit.timeit(add_array, number= 100))

0.11626239999895915


In [55]:
def add_list():
    li1 = list(range(10000))
    li2 = list(range(10000))
    
    li3 =[]
    for i in range(10000):
        li3.append(li1[i] +li2[i])
        
    return li3   

In [52]:
print(timeit.timeit(add_list, number =100))

0.1020398000109708


In [57]:
print(timeit.timeit(add_array, number= 1000))
print(timeit.timeit(add_list, number =1000))

1.1321941000060178
0.9075548999971943


- 2차원 만들기

In [63]:
np.array([[1,2,3,4],[5,6,7,8]]) #2차원 중첩리스트

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [64]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.arange(10).reshape(  (2,5)  ) # 2행 5열 쉐이프 2x5니 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [66]:
np.arange(10).reshape(  (5,2)  )

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [67]:
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
np.arange(12).reshape(3, -1) # -1은 자동으로 계산

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
np.arange(12).reshape(3, ) # -1은 자동으로 계산

ValueError: cannot reshape array of size 12 into shape (3,)

In [77]:
np.arange(24).reshape(2,3,4) # 3행 4열이 두개 나옴 2가 z축이니까 3이 y/ 4는x
# 종이가 2장 겹침 

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [78]:
np.arange(36).reshape(3,4,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [79]:
element wise 원소들 끼리 계산 가능하다. 
리스트 연산은 반복문 돌리지만 넘파이 어레이는 원소 바로 더할 수 있다.

SyntaxError: invalid syntax (1120010251.py, line 1)

In [83]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)
print(a+b)
a**b

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]


array([[    1,    64],
       [ 2187, 65536]])

In [84]:
print(a)
c =np. array([5,6])

[[1 2]
 [3 4]]


In [86]:
a

array([[1, 2],
       [3, 4]])

In [87]:
c 

array([5, 6])

In [88]:
a+c # 5,6을 자동으로 맞춰서 함 

array([[ 6,  8],
       [ 8, 10]])

In [89]:
d =np. array([5])
a+d

array([[6, 7],
       [8, 9]])

In [91]:
a+5 # 정수 5를 array로 만듬 

array([[6, 7],
       [8, 9]])

In [92]:
a + np.array([5,6,7])

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [99]:
f = np.array([[1,2,3,4],[4,5,6,7]])
g =np.array([5]) #5가 가로세로 맞춰줘서 늘림
f+g             

array([[ 6,  7,  8,  9],
       [ 9, 10, 11, 12]])

In [100]:
a[:,1] 행은 전부다 열은 1열 보기 
a[1, :] 1행 열 다봄 -1행다보기 = a[1]=a[1,] !=a[,1]

SyntaxError: invalid decimal literal (2225825507.py, line 1)

In [101]:
var[낮음, 높음, 스텝]


NameError: name 'var' is not defined

In [110]:
a= np.arange(25).reshape(5,5)
a[4,:]
a[:,1]
a[(1,3), (0,2)]

array([ 5, 17])

In [147]:
print(a[4])
print(a[:,1::2])
print(a[1::2,0: 3 :2]) # 0열에서 3열까지인데 2칸 건너띔

[20 21 22 23 24]
[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]
 [21 23]]
[[ 5  7]
 [15 17]]


In [149]:
a= np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [150]:
z차원 y행 x열

SyntaxError: invalid syntax (3368840061.py, line 1)

In [158]:
a= np.array([[1,2], [3,4]])
b= np.array([[5,6],[7,8]])
a*b

array([[ 5, 12],
       [21, 32]])

In [152]:
a= np.array([1,2, 3,4])
b= np.array([5,6,7,8])
a*b

array([ 5, 12, 21, 32])

In [163]:
np.matmul(a,b)

array([[19, 22],
       [43, 50]])

In [160]:
a@b 

array([[19, 22],
       [43, 50]])

In [162]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [165]:
import numpy as np 

a= np.arange(50).reshape(5,10)

print(a[2:5:2, 1:6:2])

[[21 23 25]
 [41 43 45]]
