# 정리

In [ ]:
li =["", "1", "12", "123", "1234", "abc", "1a"]
for string in li: 
    print(re.sub(r"[0-9]?", "A", string), end =",   ")
    
data = '''
  <head>
    <title>hello world</title>
  </head>
''' 

p= re.compile('(?<=>).*(?=</)')
p.findall(data)

def fac(n):
    if n ==1:
        return 1
    return n*fac(n-1) # 54321

def factorial(n):
    sum=1
    for i in range(n):
         sum = sum*(i+1)# 1*1 , 1*2/*3 /*4 /*5~ 10
    return sum

np.ones((2,3)) # 2행 3열을 1로 가득채움 shape 형태로 채움
np.full((10,10),3) # 3으로 가득 채움
np.eye(4,3)
np.eye(4)
a= np.array([0,1,2])
np.tile(a,(3,2)) # 행은 3번 열은 2번 반복 a= np.arange(6).reshape(2,3)
np.zeros_like(a) # 형태와 데이터 타입유지하면서 0으로 채움

# 수직으로 쌓음np.vstack((a, b)) 

np.dstack((a,b))#3차원
np.hsplit(a,2) # 수평분리
np.vsplit(a,2) #수직분리

a.flatten() #평평하게 
a.ravel() #복사함 # 바뀌면 원본도 바뀜
np.where(a>7, "pass", "fail")# ifelse문과 같음
a[np.where(a<10)]

In [1]:
dot[.] 이 의미하지 않는 것은 ? /n 


SyntaxError: invalid syntax (1426567158.py, line 1)

In [2]:
import re

In [3]:
li =["", "1", "12", "123", "1234", "abc", "1a"]
for string in li: 
    print(re.sub(r"[0-9]?", "A", string), end =",   ")

A,   AA,   AAA,   AAAA,   AAAAA,   AaAbAcA,   AAaA,   

In [5]:
li =["", "1", "12", "123", "1234", "abc", "1a"]
re.sub(r"[0-9]?", "A", string)

'AAaA'

In [6]:
re.sub()

TypeError: sub() missing 3 required positional arguments: 'pattern', 'repl', and 'string'

In [47]:
import numpy as np
a= np.arange(1,101).reshape(10,10)

print(a[4::3, 3:6:2])# 중간에는 숫자가 +1 이여야 함

[[44 46]
 [74 76]]


In [22]:
import numpy as np
a = np.arange(1,101).reshape((10, 10)) 
a[[4, 4, 7,7 ], [3,5,3,5]] # 인덱싱번호줌 

array([44, 46, 74, 76])

In [23]:
a[[0,1,2,3],[6,7,8,9]] #계단으로 내려가기 좋음

array([ 7, 18, 29, 40])

In [42]:
data = '''
  <head>
    <title>hello world</title>
  </head>
''' 

p= re.compile('(?<=>).*(?=</)')
p.findall(data)

['hello world']

In [36]:
p = re.compile('(?<=<title>).*(?=</title>)')
p.findall(data) 

['hello world']

In [43]:
a = re.compile(r"(?<=>).+(?=<)")
a.findall(data) 

['hello world']

In [44]:
p = re.compile("(?<=>).+(?=<)")
re.search
(p, data) 

(re.compile(r'(?<=>).+(?=<)', re.UNICODE),
 '\n  <head>\n    <title>hello world</title>\n  </head>\n')

In [50]:
import numpy as np
a = np.arange(1,37).reshape(6, 6) 

In [51]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [53]:
a[0::2 ,1::2] # 모든 열이 아님

array([[ 2,  4,  6],
       [14, 16, 18],
       [26, 28, 30]])

In [54]:
a[: ,1::2] 

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24],
       [26, 28, 30],
       [32, 34, 36]])

In [56]:
a = np.arange(1,100).reshape(3, 3, -1) 

In [57]:
a

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
        [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]],

       [[34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66]],

       [[67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88],
        [89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [58]:
type("100.0")


str

In [61]:
def fac(n):
    if n ==1:
        return 1
    return n*fac(n-1) # 54321

In [62]:
def fac(n):
    multi =1

In [75]:
def factorial(n):
    sum=1
    for i in range(n):
         sum = sum*(i+1)# 1*1 , 1*2/ 2*3 6*4 24*5
    return sum

In [76]:
factorial(5)

120

In [303]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [301]:
a = np.array([[1,2,3,4], [5,6,7,8]])
b= np.array([1], [2]) # 행과 열 한개일때만 괜춘
a+b

TypeError: Field elements must be 2- or 3-tuples, got '2'

In [302]:
a = np.array([[1,2,3,4], [5,6,7,8]])
b= np.array([1]) # 행과 열 한개일때만 괜춘
a+b

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [82]:
np.linspace(1,10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [86]:
np.linspace(1, 9, 5)

array([1., 3., 5., 7., 9.])

In [89]:
np.ones((2,3)) # 2행 3열을 1로 가득채움 shape 형태로 채움

array([[1., 1., 1.],
       [1., 1., 1.]])

In [91]:
np.ones((2,3), dtype='int16')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [92]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [97]:
#sparse matrix 드문 매트릭스 희귀행렬  
a= np.zeros((10,10))
a[3,3]= 1
a[5,6]=1

In [98]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [100]:
a= np.ones((10,10))
a*3

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [101]:
np.ones((10,10))*3

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [304]:
a=np.ones((10,10))*np.array([3])

In [102]:
np.full((10,10),3)

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [104]:
a= diag([1,2,3])
a

NameError: name 'diag' is not defined

In [105]:
d= np.identity(4)
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [106]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [107]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [109]:
a= np.array([0,1,2])
np.tile(a,2) # 2번반복

array([0, 1, 2, 0, 1, 2])

In [305]:
a= np.array([0,1,2])
np.tile(a,(3,2)) # 행은 3번 열은 2번 반복 

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [317]:
np.empty((2,3)) #null에 해당하는 주소값 2행 3열

array([[2.12199579e-314, 6.36598737e-314, 1.06099790e-313],
       [2.33419537e-313, 2.75859453e-313, 3.18299369e-313]])

In [114]:
a= np.arange(6).reshape(2,3)
np.zeros_like(a) # 형태와 데이터 타입유지하면서 0으로 채움

array([[0, 0, 0],
       [0, 0, 0]])

In [117]:
a=[1,2,3,4]
b=a
a.copy()
import copy# 카피라는 모듈 가져와 사용
copy.copy(a)

[1, 2, 3, 4]

In [125]:
a=np.array([1,2,3,4])
b=a
c= a.copy()
d= copy.copy(a)

In [119]:
b[0]=100

In [120]:
b

array([100,   2,   3,   4])

In [121]:
c

<function ndarray.copy>

In [122]:
d

array([1, 2, 3, 4])

In [310]:
np.arange(1,9,2) # 9는 제외

array([1, 3, 5, 7])

In [127]:
np.linspace(0,1,6) # 1은 포함 함수가 다름

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [313]:
np.ones((3,3),int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [129]:
stack 맨처음 들어간게 맨막자막
stack이란 FIL 선착순 반대
ctrl -  z  쌓여있으니까 맨마지막이 처음

SyntaxError: invalid syntax (1701443209.py, line 1)

In [130]:
[0,10,20,30,40,50,60,70,80,90]


[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]

In [315]:
a= np.arange(10)*10
a= np.arange(10)*20

In [137]:
# 수직으로 쌓음np.vstack((a, b)) 

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 10 and the array at index 1 has size 4

In [316]:
np.hstack((a, b)) 

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180,   1])

In [140]:
np.hstack((a, b)).shape # shape는 몇행 몇열인지 알려줌 

(14,)

In [318]:
a=np.array([[1],[2],[3]])


In [319]:
a

array([[1],
       [2],
       [3]])

In [321]:
a=np.array([[1],[2],[3]])
print(a.shape)
b=np.array([[1],[2],[3]])


(3, 1)


In [323]:
np.hstack((a,b))

array([[1, 1],
       [2, 2],
       [3, 3]])

In [322]:
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [1],
       [2],
       [3]])

In [149]:
np.dstack((a,b))#3차원

array([[[1, 1]],

       [[2, 2]],

       [[3, 3]]])

In [380]:
a =np.arange(32).reshape(4,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [152]:
np.hsplit(a,2) # 수평분리

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19],
        [24, 25, 26, 27]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]])]

In [354]:
np.vsplit(a,2) #수직분리

[array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]])]

In [355]:
a.shape

(4, 8)

In [382]:
a.flatten() #평평하게 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [383]:
a.flatten().shape 

(32,)

In [384]:
a.ravel() #복사함 # 바뀌면 원본도 바뀜

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [386]:
a.T # 4행 8열에서 8행 4열로 바꿈 

array([[ 0,  8, 16, 24],
       [ 1,  9, 17, 25],
       [ 2, 10, 18, 26],
       [ 3, 11, 19, 27],
       [ 4, 12, 20, 28],
       [ 5, 13, 21, 29],
       [ 6, 14, 22, 30],
       [ 7, 15, 23, 31]])

In [162]:
np.transpose(a)

array([[ 0,  8, 16, 24],
       [ 1,  9, 17, 25],
       [ 2, 10, 18, 26],
       [ 3, 11, 19, 27],
       [ 4, 12, 20, 28],
       [ 5, 13, 21, 29],
       [ 6, 14, 22, 30],
       [ 7, 15, 23, 31]])

In [163]:
a = np.arange(1,5).reshape(2,2)
a.T 


array([[1, 3],
       [2, 4]])

In [364]:
c = np.vstack((a,a))
np.vsplit(c,2) 

[array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]]),
 array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]])]

In [365]:
#비교 
a = np.array([1,2,3,4])
b= np.array([1,2,3,4])              

In [169]:
a[ :]

array([1, 2, 3, 4])

In [171]:
a[::-1]

array([4, 3, 2, 1])

In [366]:
a= np.array([[2,1,6],[0,7,4], [5,3,2]])
a

array([[2, 1, 6],
       [0, 7, 4],
       [5, 3, 2]])

In [182]:
np.sort(a) # 세로를 기준으로 바꿈 

array([[1, 2, 6],
       [0, 4, 7],
       [2, 3, 5]])

In [184]:
np.sort(a, axis=0) #가로를 기준으로 열만 생각해서 바뀜 

array([[0, 1, 2],
       [2, 3, 4],
       [5, 7, 6]])

In [186]:
np.sort(a, axis=1) # 1이 기본값

array([[1, 2, 6],
       [0, 4, 7],
       [2, 3, 5]])

In [187]:
a = np.arange(6).reshape(1,-1)
b = np.arange(10,16).reshape(1,-1)
c = np.arange(20,26).reshape(1,-1)
d = np.arange(30,36).reshape(1,-1)
e = np.arange(40,46).reshape(1,-1)
f = np.arange(50,56).reshape(1,-1)
np.vstack((a,b,c,d,e,f)) 

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [230]:
a = np.arange(100).reshape(10,10)
a = a[0:6:1,0:6:1] # 전체를 한다음 자름 

In [217]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [229]:
a = np.array([0,1,2,3,4,5])
b = np.array([[0],[10],[20],[30],[40],[50]])
a+b 

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [248]:
a = np.arange(6)
array = a.copy()
for i in range(5):
    i+=1
    array = np.vstack((array, a+10*i))# array랑 쌓는것 뒤에씀 10부터 50까지 쌓음 
array                         #i가 0이면 array가 두개 쌓임

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [395]:
a= np.arange(1,5)
array = a.copy()
for i in range(3):
    i+=1
    array =np.vstack((array, a*10*i))
array    

array([[  1,   2,   3,   4],
       [ 10,  20,  30,  40],
       [ 20,  40,  60,  80],
       [ 30,  60,  90, 120]])

In [397]:
array[np.where(array>20)]

array([ 30,  40,  40,  60,  80,  30,  60,  90, 120])

In [368]:
a = np.arange(6)
array = a.copy()
for i in range(1,6):
    array = np.vstack((array, a+10*i))# 만약 a라면 두줄 더하기 두줄이됨 
    print(array)                      # 계속 급수적으로 늘어남 
    print("--"*10)                    # array여야 a가 아니니 한줄씩 추가 
array    
    

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]]
--------------------
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]]
--------------------
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]]
--------------------
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]]
--------------------
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
--------------------


array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [373]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [372]:
np.arange(0,55).reshape(5,-1) # reshape이 안됨

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54]])

In [209]:
a[4: , 4:]
a[0,3:5]
a[::,2]
a[2::2,0::2] 

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [207]:
a[:, 2]
a[0, 3:5]
a[2:5:2, 0:5:2]
a[4:, 4:] 

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [210]:
arr[2] -행 전체를 가리킴 

SyntaxError: invalid syntax (2280169642.py, line 1)

In [370]:
a[:2] #0과 1행 보여줌

array([0, 1])

In [374]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [375]:
a[[1,2,-5]]

array([1, 2, 1])

In [376]:
indices = [1,2,-3] # 인덱스번호만 따로 묶음
a[indices]

array([1, 2, 3])

In [242]:
a =np.arange(8)+10
a

array([10, 11, 12, 13, 14, 15, 16, 17])

In [243]:
a =np.arange(8)*10
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [237]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [224]:
a[[1,2,-3]]

array([10, 20, 50])

In [225]:
indices = [1,2,-3] # 인덱스번호만 따로 묶음
a[indices]

array([10, 20, 50])

In [226]:
mask=[False, True, True, False,False,True,False,False ]
a[mask]

array([10, 20, 50])

In [377]:
np.array([0,1,1,0,0,1,0,0])

array([0, 1, 1, 0, 0, 1, 0, 0])

In [227]:
mask =np.array([0,1,1,0,0,1,0,0], dtype=bool)#false =0 
mask             

array([False,  True,  True, False, False,  True, False, False])

In [232]:
[a[0,1], a[1,2], a[2,0] ,a[2,3]]

[1, 12, 20, 23]

In [233]:
a[[0,1,2,2], [1,2,0,3]]

array([ 1, 12, 20, 23])

In [378]:
b= np.arange(25).reshape(5,5)
b[[0,1,2,3],[1,2,3,4]]

array([ 1,  7, 13, 19])

In [255]:
a = np.array([[1,2,3],[4,5,6]])

In [256]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [259]:
import numpy
sum(a)

TypeError: 'numpy.ndarray' object is not callable

In [258]:
np.sum(a)

21

In [260]:
np.sum(a, axis=0) # 세로로 계산

array([5, 7, 9])

In [263]:
np.sum(a, axis=1) #가로 계산

array([ 6, 15])

In [264]:
np.min(a) #전체중 최소

1

In [265]:
np.min(a, axis=0)

array([1, 2, 3])

In [266]:
np.argmin(a) #1234566 중에 최소값인덱스 0 

0

In [268]:
np.argmax(a) # 123456중에 최대값 인덱스 5 1차원으로 만든후 

5

In [269]:
a= np.array([1,2,3])
b = np.array([4,5,6])
a+b

array([5, 7, 9])

In [270]:
a**b

array([  1,  32, 729])

In [271]:
np.sin(a) # 각각에 대해 sin값

array([0.84147098, 0.90929743, 0.14112001])

In [272]:
np.max(a)

3

In [273]:
np.where() #참일때실행 것짓일떄 뭐 인덱스가 나옴

TypeError: where() missing 1 required positional argument: 'condition'

In [379]:
a=np.array([6,7,8,9,10])
np.where(a>7) # 인덱스 번호 나옴 

(array([2, 3, 4], dtype=int64),)

In [278]:
a[np.where(a>7)] # where가 인덱스 번호니 안에 넣어줌 

array([ 8,  9, 10])

In [279]:
ifelse(a>70, "pass", "fail")# 

NameError: name 'ifelse' is not defined

In [280]:
np.where(a>7, "pass", "fail")# ifelse문과 같음

array(['fail', 'fail', 'pass', 'pass', 'pass'], dtype='<U4')

In [281]:
a=np.arange(-15,15).reshape(5,6)**2

In [282]:
a

array([[225, 196, 169, 144, 121, 100],
       [ 81,  64,  49,  36,  25,  16],
       [  9,   4,   1,   0,   1,   4],
       [  9,  16,  25,  36,  49,  64],
       [ 81, 100, 121, 144, 169, 196]])

In [283]:
np.arange(-15,15)

array([-15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,
        -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
        11,  12,  13,  14])

In [285]:
np.max(a, axis=1) # 일은 수평

array([225,  81,   9,  64, 196])

In [286]:
np.mean(a, axis=0)

array([81., 76., 73., 72., 73., 76.])

In [287]:
a[np.where(a<10)]

array([9, 4, 1, 0, 1, 4, 9])

In [290]:
np.where(a<10,0,1)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [292]:
#넘파이는 c로 만들어져 있어서 빠르다. 
#넘파이는 새로 만들지 않음
#strides 8, 24는 8x3 3칸뜀  